LOAD 'age';

SET work_mem TO '32MB';
SET max_parallel_workers_per_gather = 4;
SET search_path = ag_catalog, "$user", public;

-- Create new graph if missing.
SELECT * FROM create_graph('general');

-- Populate with initial data.
SELECT * FROM cypher('general', $$
    CREATE (:AutoimmuneDisorder {type: 'Autoimmune Disorders'})-[:ENCOMPASSES]->(:Disorder {type: 'Multiple Sclerosis'})
    CREATE (:AutoimmuneDisorder {type: 'Autoimmune Disorders'})-[:ENCOMPASSES]->(:Disorder {type: 'Rheumatoid Arthritis'})
    CREATE (:Dementia {type: 'Dementia'})-[:IS_A]->(:Disorder {type: 'Neurodegenerative Disorder'})
    CREATE (:Diet {type: 'Dietary Intake of n-3 Polyunsaturated Fatty Acids'})-[:REDUCES]->(:Symptomatology {type: 'Depressive Symptomatology'})
    CREATE (:Diet {type: 'Dietary Sugar Intake'})-[:AFFECTS]->(:BodyFunction {type: 'Liver Function'})
    CREATE (:Diet {type: 'Excessive Sugar Consumption'})-[:INCREASES_RISK_OF]->(:Disorder {type: 'Hepatic Disease'})
    CREATE (:Diet {type: 'Excessive Sugar Consumption'})-[:INCREASES_RISK_OF]->(:Disorder {type: 'Non-Alcoholic Fatty Liver Disease (NAFLD)'})
    CREATE (:Diet {type: 'High Dietary Fiber Consumption'})-[:REDUCES_RISK_OF]->(:Disease {type: 'Cancer Incidence'})
    CREATE (:Diet {type: 'High Dietary Fiber Consumption'})-[:REDUCES_RISK_OF]->(:Disease {type: 'Cardiovascular Disease'})
    CREATE (:Diet {type: 'High Dietary Fiber Consumption'})-[:REDUCES_RISK_OF]->(:Disease {type: 'Type 2 Diabetes Mellitus'})
    CREATE (:Diet {type: 'Mediterranean Dietary Pattern'})-[:COMPRISES]->(:FOOD {type: 'Fresh Fruits'})
    CREATE (:Diet {type: 'Mediterranean Dietary Pattern'})-[:COMPRISES]->(:FOOD {type: 'Whole Grain Foods'})
    CREATE (:Diet {type: 'Mediterranean Dietary Pattern'})-[:REDUCES_RISK_OF]->(:Disorder {type: 'Dementia'})
    CREATE (:Diet {type: 'Mediterranean Dietary Pattern'})-[:REDUCES_RISK_OF]->(:Impairment {type: 'Cognitive Impairment'})
    CREATE (:Diet {type: 'Total Dietary Fiber'})-[:REDUCES_RISK_OF]->(:Disease {type: 'Non-Communicable Diseases'})
    CREATE (:Diet {type: 'Vegetarian Diet Pattern'})-[:LEADS_TO]->(:Health {type: 'Cardiovascular Disease Risk Reduction'})
    CREATE (:Diet {type: 'Vegetarian Diet Pattern'})-[:PROMOTES]->(:Health {type: 'Cardiovascular Health'})
    CREATE (:Diet {type: 'Vegetarian Diet Pattern'})-[:REDUCES_RISK_OF]->(:Disease {type: 'Cardiovascular Disease'})
    CREATE (:Disease {type: 'Cardiovascular Disease'})-[:IS_A]->(:Disease {type: 'Chronic Non-Communicable Disease'})
    CREATE (:Disease {type: 'Hepatic Disease'})-[:ENCOMPASSES]->(:Disorder {type: 'Non-Alcoholic Fatty Liver Disease (NAFLD)'})
    CREATE (:Disease {type: 'Leaky Gut Syndrome'})-[:IS_CHARACTERIZED_BY]->(:BiologicalProcess {type: 'Intestinal Permeability'})
    CREATE (:DiseaseState {type: 'Dysbiosis'})-[:INCREASES]->(:BiologicalProcess {type: 'Intestinal Permeability'})
    CREATE (:DiseaseState {type: 'Dysbiosis'})-[:IS_IMBALANCE_OF]->(:Microbiome {type: 'Gut Microbiome'})
    CREATE (:DiseaseState {type: 'Dysbiosis'})-[:LEADS_TO]->(:Disease {type: 'Leaky Gut Syndrome'})
    CREATE (:DiseaseState {type: 'Dysbiosis'})-[:LINKED_TO]->(:Disease {type: 'Diabetes Mellitus'})
    CREATE (:DiseaseState {type: 'Dysbiosis'})-[:LINKED_TO]->(:Disease {type: 'Inflammatory Bowel Disease'})
    CREATE (:DiseaseState {type: 'Dysbiosis'})-[:LINKED_TO]->(:Disease {type: 'Obesity'})
    CREATE (:FoodProduct {type: 'Ultra-processed food products'})-[:CONTRIBUTES_TO]->(:Disorder {type: 'Cognitive Decline'})
    CREATE (:FoodProduct {type: 'Ultra-processed food products'})-[:INCLUDES]->(:FoodProduct {type: 'Frozen Meals'})
    CREATE (:FoodProduct {type: 'Ultra-processed food products'})-[:INCLUDES]->(:FoodProduct {type: 'Packaged Snack Foods'})
    CREATE (:FoodProduct {type: 'Ultra-processed food products'})-[:INCREASES]->(:Disease {type: 'Dementia Risk'})
    CREATE (:FoodProduct {type: 'Ultra-processed food products'})-[:LINKED_TO]->(:Disease {type: 'Dementia'})
    CREATE (:FoodProduct {type: 'Ultra-processed food products'})-[:POSES]->(:FoodProduct {type: 'Chronic Disease Risk'})
    CREATE (:Gender {type: 'Human Male'})-[:REQUIRES]->(:Vitamins {type: 'Vitamin C'})
    CREATE (:Health {type: 'Gastrointestinal Health'})-[:INFLUENCES]->(:ImmuneSystem {type: 'Immune System Function'})
    CREATE (:ImmuneSystem {type: 'Immune System Function'})-[:IS_RELATED_TO]->(:Disorder {type: 'Autoimmune Disorders'})
    CREATE (:Microbiome {type: 'Gut Microbiome'})-[:BREAKS_DOWN]->(:Macronutrient {type: 'Fats'})
    CREATE (:Microbiome {type: 'Gut Microbiome'})-[:BREAKS_DOWN]->(:Macronutrient {type: 'Polysaccharides'})
    CREATE (:Microbiome {type: 'Gut Microbiome'})-[:BREAKS_DOWN]->(:Macronutrient {type: 'Proteins'})
    CREATE (:Microbiome {type: 'Gut Microbiome'})-[:COMPOSED_OF]->(:Microorganism {type: 'Gut Microorganisms'})
    CREATE (:Microbiome {type: 'Gut Microbiome'})-[:CONTRIBUTES_TO]->(:BiologicalProcess {type: 'Nutrient Metabolism'})
    CREATE (:Microbiome {type: 'Gut Microbiome'})-[:LOCATED_IN]->(:BiologicalSystem {type: 'Gastrointestinal Tract (GIT)'})
    CREATE (:Microbiome {type: 'Gut Microbiome'})-[:MAINTAINS]->(:BiologicalSystem {type: 'Gastrointestinal Barrier'})
    CREATE (:Microbiome {type: 'Gut Microbiome'})-[:PRODUCES]->(:Vitamin {type: 'Biotin'})
    CREATE (:Microbiome {type: 'Gut Microbiome'})-[:PRODUCES]->(:Vitamin {type: 'Vitamin K'})
    CREATE (:Microbiome {type: 'Gut Microbiome'})-[:SUPPORTS]->(:BiologicalProcess {type: 'Immune Function'})
    CREATE (:Microbiota {type: 'Gastrointestinal Microbiota'})-[:INFLUENCES]->(:Disorder {type: 'Autoimmune Disorders'})
    CREATE (:Microbiota {type: 'Gastrointestinal Microbiota'})-[:REGULATES]->(:ImmuneSystemFunction {type: 'Immune System Function'})
    CREATE (:Microorganism {type: 'Gut Microorganisms'})-[:INCLUDES]->(:Bacteria {type: 'Gut Bacteria'})
    CREATE (:Microorganism {type: 'Gut Microorganisms'})-[:INCLUDES]->(:Fungi {type: 'Gut Fungi'})
    CREATE (:Microorganism {type: 'Gut Microorganisms'})-[:INCLUDES]->(:Virus {type: 'Gut Viruses'})
    CREATE (:Molecule {type: 'Docosahexaenoic Acid (DHA)'})-[:IS_A_TYPE_OF]->(:PolyunsaturatedFattyAcids {type: 'n-3 Polyunsaturated Fatty Acids'})
    CREATE (:Molecule {type: 'Eicosapentaenoic Acid (EPA)'})-[:IS_A_TYPE_OF]->(:PolyunsaturatedFattyAcids {type: 'n-3 Polyunsaturated Fatty Acids'})
    CREATE (:PolyunsaturatedFattyAcids {type: 'n-3 Polyunsaturated Fatty Acids'})-[:IMPROVES]->(:CognitiveFunction {type: 'Cognitive Function'})
    CREATE (:State {type: 'Immunocompromised'})-[:BENEFITS_FROM]->(:Supplements {type: 'Probiotic'})
    CREATE (:Study {type: 'Epidemiological Study'})-[:PUBLISHED_IN]->(:Journal {type: 'The Lancet Journal'})
    CREATE (:Supplement {type: 'Probiotic'})-[:ENHANCES]->(:ImmuneSystem {type: 'Immune System Function'})
    CREATE (:Supplement {type: 'Probiotic'})-[:IMPROVES]->(:Health {type: 'Gastrointestinal Health'})
    CREATE (:Symptom {type: 'Hypozincemia'})-[:INCREASES_RISK_OF]->(:Infection {type: 'Bronchitis'})
    CREATE (:Symptom {type: 'Hypozincemia'})-[:INCREASES_RISK_OF]->(:Infection {type: 'Respiratory Tract Infections'})
    CREATE (:Symptom {type: 'Hypozincemia'})-[:INCREASES_RISK_OF]->(:InflammatoryCondition {type: 'Pneumonia'})
    CREATE (:Vitamin {type: 'Vitamin D'})-[:PLAYS_ROLE_IN]->(:ImmuneSystem {type: 'Immune Function Regulation'})
    CREATE (:VitaminDeficiency {type: 'Hypovitaminosis D'})-[:INCREASES_RISK_OF]->(:Disorder {type: 'Autoimmune Disorders'})
$$) AS (a agtype);
