SELECT * FROM create_graph('healthy_diet_part2of2');
SELECT * FROM cypher('healthy_diet_part2of2', $$
    CREATE (:AgeGroup {type: 'Pediatric Age Groups'})-[:INCLUDES]->(:AgeRange {type: 'Adolescence', ageRange: '10 years or older'})
    CREATE (:AgeGroup {type: 'Pediatric Age Groups'})-[:INCLUDES]->(:AgeRange {type: 'Early Childhood', ageRange: '2-5 years'})
    CREATE (:AgeGroup {type: 'Pediatric Age Groups'})-[:INCLUDES]->(:AgeRange {type: 'Middle Childhood', ageRange: '6-9 years'})
    CREATE (:ArtificialSweeteners)-[:REGULATED_BY]->(:WHODietaryGuidelines)
    CREATE (:BalancedDiets {type: 'Balanced Diets'})-[:REQUIRES]->(:EnergyBalance {type: 'Energy Balance'})
    CREATE (:Carbohydrate {type: 'Carbohydrates'})-[:COMES_FROM]->(:ComplexCarbohydrate {type: 'Complex Carbohydrates'})
    CREATE (:Carbohydrate {type: 'Complex Carbohydrates'})-[:IS_A_SUBTYPE_OF]->(:Macronutrient {type: 'Carbohydrates'})
    CREATE (:ComplementaryNutrition {type: 'Complementary Nutrition'})-[:SUPPORTS]->(:InfantAndYoungChildNutrition {type: 'Infant and Young Child Nutrition'})
    CREATE (:Diet {type: 'Diverse Diets'})-[:FAVORS]->(:Nutrient {type: 'Nutrient Adequacy'})
    CREATE (:Diet {type: 'Healthy Diets'})-[:PREVENTS]->(:Disease {type: 'Chronic Diseases'})
    CREATE (:Diet {type: 'Healthy Diets'})-[:PREVENTS]->(:Disease {type: 'Foodborne Illnesses'})
    CREATE (:Diet {type: 'Healthy Diets'})-[:PREVENTS]->(:Disease {type: 'Micronutrient Deficiencies'})
    CREATE (:DietQuality)-[:RELATED_TO]->(:FoodBiodiversity)
    CREATE (:DietQualityIndex)-[:ASSOCIATED_WITH_RISK_OF]->(:CoronaryHeartDisease)
    CREATE (:DietaryDiversity)-[:ASSESSED_IN]->(:WomenOfReproductiveAge)
    CREATE (:DietaryDiversity)-[:PREDICTS]->(:MicronutrientIntake)
    CREATE (:DietaryDiversity)-[:RECOMMENDED_FOR]->(:WomensNutrition)
    CREATE (:DietaryDiversity)-[:RELATED_TO]->(:AllCauseMortality)
    CREATE (:DietaryDiversityScore {type: 'Dietary Diversity Scores'})-[:ASSOCIATES_WITH]->(:DietaryAdequacy {type: 'Dietary Adequacy'})
    CREATE (:DietaryGuidelines)-[:CHARACTERIZE]->(:HealthyEatingPatterns)
    CREATE (:DietaryReferenceIntake {type: 'Estimated Average Requirement (EAR)'})-[:SETS]->(:DietaryReferenceIntake {type: 'Dietary Reference Intake (DRI)'})
    CREATE (:DietaryVariety)-[:INCLUDES]->(:FoodCategoryVariety)
    CREATE (:EatingPattern {type: 'Moderate Eating'})-[:MINIMIZES]->(:HealthEffect {type: 'Adverse Health Effects'})
    CREATE (:EatingPatterns)-[:COMPOSED_OF]->(:FoodCategories)
    CREATE (:EatingPatterns)-[:INFLUENCED_BY]->(:SocioEnvironmentalFactors)
    CREATE (:EnergyBalance {type: 'Energy Balance'})-[:BALANCED_WITH]->(:NutrientIntake {type: 'Carbohydrate Intake'})
    CREATE (:EnergyBalance {type: 'Energy Balance'})-[:BALANCED_WITH]->(:NutrientIntake {type: 'Fat Intake'})
    CREATE (:EnergyBalance {type: 'Energy Balance'})-[:BALANCED_WITH]->(:NutrientIntake {type: 'Protein Intake'})
    CREATE (:EnergyRequirement {type: 'Energy Requirements'})-[:DETERMINES]->(:NutrientIntake {type: 'Nutrient Intake'})
    CREATE (:EssentialFattyAcids {type: 'Essential Fatty Acids'})-[:OBTAINED_FROM]->(:Diet {type: 'Diet'})
    CREATE (:FAOMinimumDietaryDiversityWomen)-[:PROXY_OF]->(:MicronutrientIntake)
    CREATE (:FatsAndFattyAcids {type: 'Fats and Fatty Acids'})-[:IS_IMPORTANT_FOR]->(:HumanNutrition {type: 'Human Nutrition'})
    CREATE (:FattyAcid {type: 'Monounsaturated And Polyunsaturated Fatty Acids'})-[:IS_A_TYPE_OF]->(:DietaryComponent {type: 'Dietary Fat'})
    CREATE (:FattyAcid {type: 'Omega 3 Fatty Acids'})-[:IS_A_TYPE_OF]->(:FattyAcid {type: 'Polyunsaturated Fatty Acids'})
    CREATE (:FattyAcid {type: 'Omega 6 Fatty Acids'})-[:IS_A_TYPE_OF]->(:FattyAcid {type: 'Polyunsaturated Fatty Acids'})
    CREATE (:FattyAcid {type: 'Polyunsaturated Fatty Acids'})-[:IS_A_SUBTYPE_OF]->(:FattyAcid {type: 'Monounsaturated And Polyunsaturated Fatty Acids'})
    CREATE (:FattyAcid {type: 'Polyunsaturated Fatty Acids'})-[:REPLACES]->(:FattyAcid {type: 'Saturated Fatty Acids'})
    CREATE (:FattyAcid {type: 'Saturated Fatty Acids'})-[:PART_OF]->(:Nutrient {type: 'Total Fat'})
    CREATE (:FattyAcid {type: 'Trans Fatty Acids'})-[:PART_OF]->(:Nutrient {type: 'Total Fat'})
    CREATE (:Fibre {type: 'Dietary Fibre'})-[:OCCURS_IN]->(:Food {type: 'Whole Foods'})
    CREATE (:Food {type: 'Animal-Derived Foods'})-[:PROVIDES]->(:Protein {type: 'High-Quality Protein'})
    CREATE (:Food {type: 'Fiber Rich Foods'})-[:IS_A_TYPE_OF]->(:Carbohydrate {type: 'Complex Carbohydrates'})
    CREATE (:Food {type: 'Food Safety'})-[:PREVENTS]->(:Disease {type: 'Foodborne Illnesses'})
    CREATE (:Food {type: 'Fruits And Vegetables'})-[:PART_OF]->(:Diet {type: 'Diet'})
    CREATE (:Food {type: 'Ultra Processed Foods'})-[:IS_ASSOCIATED_WITH]->(:HealthRisk {type: 'Chronic Disease Risk'})
    CREATE (:FoodAndAgricultureOrganization)-[:COLLABORATES_WITH]->(:WorldHealthOrganization)
    CREATE (:FoodBasedDietaryGuideline {type: 'Food-Based Dietary Guidelines'})-[:DEVELOPS_WITH]->(:FoodSystemsApproach {type: 'Food Systems Approach'})
    CREATE (:FoodBasedDietaryGuideline {type: 'Food-Based Dietary Guidelines'})-[:UNDERGOES]->(:GlobalReview {type: 'Global Review'})
    CREATE (:FoodBiodiversity)-[:MEASURES]->(:DietaryDiversity)
    CREATE (:FoodCategories)-[:DIFFER_IN_CONTENT_AND_DENSITY_OF]->(:EssentialNutrients)
    CREATE (:FoodCompositionDatabaseForBiodiversity)-[:VERSION_OF]->(:BioFoodComp4)
    CREATE (:FoodGroupDiversity)-[:PREDICTS]->(:MicronutrientAdequacy)
    CREATE (:FoodSafetyGuideline {type: 'Food Safety Guidelines'})-[:ENSURES]->(:FoodSafety {type: 'Food Safety'})
    CREATE (:FoodSystems)-[:HAS]->(:EnvironmentalSustainability)
    CREATE (:FoodSystems)-[:IMPACT_AND_SHAPE]->(:EatingPatterns)
    CREATE (:Guideline {type: 'Added Sugar Guidelines'})-[:ADVOCATES]->(:Recommendation {type: 'Reduced Sugar Intake'})
    CREATE (:Guideline {type: 'Dietary Fiber Guidelines'})-[:CATEGORIZED_BY]->(:AgeGroup {type: 'Pediatric Age Groups'})
    CREATE (:Guideline {type: 'Potassium Intake Guidelines'})-[:AIMS_TO]->(:DiseasePrevention {type: 'Cardiovascular Disease Prevention'})
    CREATE (:Guideline {type: 'Sodium Intake Guidelines'})-[:AIMS_TO]->(:DiseasePrevention {type: 'Cardiovascular Disease Prevention'})
    CREATE (:Harmonization {type: 'Harmonization'})-[:AIMS_TO_STANDARDIZE]->(:MethodologicalApproach {type: 'Methodological Approaches'})
    CREATE (:HealthyEatingPattern {type: 'Healthy Eating Patterns'})-[:IS]->(:SustainableDiet {type: 'Sustainable Diets'})
    CREATE (:HealthyEatingPattern {type: 'Healthy Eating Patterns'})-[:PROMOTES]->(:FoodSecurity {type: 'Food Security'})
    CREATE (:HealthyEatingPattern {type: 'Healthy Eating Patterns'})-[:SUPPORTS]->(:ChronicDiseasePrevention {type: 'Chronic Disease Prevention'})
    CREATE (:HealthyEatingPatterns {type: 'Healthy Eating Patterns'})-[:BASED_ON]->(:KeyCharacteristicsOfHealthyDiets {type: 'Key Characteristics of Healthy Diets'})
    CREATE (:HealthyEatingPatterns {type: 'Healthy Eating Patterns'})-[:ENDORSED_BY]->(:Organization {type: 'Food and Agriculture Organization of the United Nations'})
    CREATE (:HealthyEatingPatterns {type: 'Healthy Eating Patterns'})-[:ENDORSED_BY]->(:Organization {type: 'World Health Organization'})
    CREATE (:HealthyEatingPatterns {type: 'Healthy Eating Patterns'})-[:LICENSED_UNDER]->(:CreativeCommonsAttributionNonCommercialShareAlike3IGO {type: 'Creative Commons Attribution-NonCommercial-ShareAlike 3.0 IGO'})
    CREATE (:HealthyEatingPatterns)-[:COMPRISED_OF]->(:SafeFoods)
    CREATE (:HealthyEatingPatterns)-[:DESCRIBED_IN]->(:JointStatement)
    CREATE (:InfantAndYoungChildNutrition)-[:ASSESSED_BY]->(:NutritionIndicators)
    CREATE (:KeyCharacteristicsOfHealthyDiets {type: 'Key Characteristics of Healthy Diets'})-[:INCLUDES]->(:DietaryVariety {type: 'Dietary Variety'})
    CREATE (:KeyCharacteristicsOfHealthyDiets {type: 'Key Characteristics of Healthy Diets'})-[:INCLUDES]->(:EnergyBalance {type: 'Energy Balance'})
    CREATE (:KeyCharacteristicsOfHealthyDiets {type: 'Key Characteristics of Healthy Diets'})-[:INCLUDES]->(:NutrientAdequacy {type: 'Nutrient Adequacy'})
    CREATE (:KeyCharacteristicsOfHealthyDiets {type: 'Key Characteristics of Healthy Diets'})-[:INCLUDES]->(:NutrientBalance {type: 'Nutrient Balance'})
    CREATE (:Macronutrient {type: 'Carbohydrates'})-[:IS_A_TYPE_OF]->(:Nutrient {type: 'Macronutrients'})
    CREATE (:MacronutrientRequirements {type: 'Macronutrient Requirements'})-[:DEFINED_BY]->(:Organization {type: 'Food And Agriculture Organization (FAO)'})
    CREATE (:MacronutrientRequirements {type: 'Macronutrient Requirements'})-[:DEFINED_BY]->(:Organization {type: 'World Health Organization (WHO)'})
    CREATE (:MethodologicalApproach {type: 'Nutrient Requirements'})-[:USES]->(:MethodologicalApproach {type: 'Methodological Approaches'})
    CREATE (:MicronutrientRequirement {type: 'Micronutrient Requirements'})-[:IS_ESSENTIAL_FOR]->(:HumanNutrition {type: 'Human Nutrition'})
    CREATE (:Mineral {type: 'Sodium'})-[:AFFECTS]->(:PhysiologicalProcess {type: 'Blood Pressure Regulation'})
    CREATE (:MinimumDietaryDiversityForWomen)-[:MEASURES]->(:DietaryVariety)
    CREATE (:MinimumDietaryDiversityWomen)-[:USED_FOR]->(:PopulationLevelAssessment)
    CREATE (:Nutrient {type: 'Added Sugars'})-[:SHOULD_BE_LIMITED_TO]->(:DailyEnergyIntake {type: 'Daily Energy Intake'})
    CREATE (:Nutrient {type: 'Essential Nutrients'})-[:SUPPORTS]->(:PhysiologicalFunction {type: 'Physiological Functions'})
    CREATE (:Nutrient {type: 'TotalFat'})-[:CONSTITUTES]->(:EnergyIntake {type: 'Total Energy Intake'})
    CREATE (:NutrientAdequacy)-[:IS_A_FUNDAMENTAL_ELEMENT_OF]->(:HealthyEatingPatterns)
    CREATE (:NutrientIntake {type: 'Fat Intake'})-[:ESSENTIAL_FOR_PROPER_FUNCTIONING_OF]->(:CellComponent {type: 'Cell Membranes'})
    CREATE (:NutrientIntake {type: 'Protein Intake'})-[:PROVIDES_BUILDING_BLOCKS_FOR]->(:Tissue {type: 'Muscle Tissue'})
    CREATE (:NutrientIntakeLevel {type: 'Nutrient Intake Levels'})-[:INVOLVES]->(:Extrapolation {type: 'Extrapolation'})
    CREATE (:NutrientRequirements {type: 'Nutrient Requirements'})-[:DESCRIBED_IN]->(:NutritionTerminology {type: 'Nutrition Terminology'})
    CREATE (:Nutrition {type: 'Adequate Nutrition'})-[:PROVIDES]->(:Nutrient {type: 'Essential Nutrients'})
    CREATE (:Nutrition {type: 'Balanced Nutrition'})-[:REGULATES]->(:PhysiologicalProcess {type: 'Energy Balance'})
    CREATE (:Organization {type: 'Food and Agriculture Organization of the United Nations'})-[:COLLABORATES_WITH]->(:Organization {type: 'World Health Organization'})
    CREATE (:Organization {type: 'Food and Agriculture Organization'})-[:PROVIDES]->(:Recommendation {type: 'Nutrient Recommendations'})
    CREATE (:Organization {type: 'National Academies Of Sciences Engineering And Medicine'})-[:PROVIDES]->(:Recommendation {type: 'Nutrient Recommendations'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PROVIDES]->(:Guideline {type: 'Added Sugar Guidelines'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PROVIDES]->(:Guideline {type: 'Dietary Fiber Guidelines'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PROVIDES]->(:Guideline {type: 'Potassium Intake Guidelines'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PROVIDES]->(:Guideline {type: 'Sodium Intake Guidelines'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PROVIDES]->(:Recommendation {type: 'Nutrient Recommendations'})
    CREATE (:PeriodicTableOfFoodInitiative)-[:GENERATES_KNOWLEDGE_OF]->(:EdibleBiodiversity)
    CREATE (:ProcessedMeat)-[:IMPACTS]->(:HumanHealthOutcomes)
    CREATE (:ProteinRequirement {type: 'Protein Requirements'})-[:IS_ESSENTIAL_FOR]->(:HumanNutrition {type: 'Human Nutrition'})
    CREATE (:ResearchMethod {type: 'Research Methods'})-[:SUPPORTS]->(:HealthOutcome {type: 'Health Outcomes'})
    CREATE (:SodiumConsumption)-[:ASSOCIATED_WITH_RISK_OF]->(:Hypertension)
    CREATE (:SustainableDiet {type: 'Sustainable Diets'})-[:FOLLOWS]->(:GuidingPrinciple {type: 'Guiding Principles'})
    CREATE (:TolerableUpperIntakeLevel {type: 'Tolerable Upper Intake Level (UL)'})-[:DETERMINES]->(:HealthOutcome {type: 'Health Outcomes'})
    CREATE (:UltraProcessedFoods)-[:LINKED_TO]->(:AdverseHealthOutcomes)
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:COLLABORATED_WITH]->(:FoodAndAgricultureOrganizationOfTheUnitedNations {type: 'Food and Agriculture Organization of the United Nations'})
    CREATE (:WorldHealthOrganization)-[:PUBLISHES]->(:NutritionGuidelines)
$$) AS (a agtype);
