SELECT * FROM create_graph('healthy_diet_part1of2');
SELECT * FROM cypher('healthy_diet_part1of2', $$
    CREATE (:Area {type: 'Urban Area'})-[:PART_OF]->(:City {type: 'City'})
    CREATE (:Behavior {type: 'Exclusive Breastfeeding'})-[:FOSTERS]->(:Outcome {type: 'Optimal Growth and Development'})
    CREATE (:Behavior {type: 'Regular Physical Activity'})-[:PART_OF]->(:Lifestyle {type: 'Healthy Lifestyle'})
    CREATE (:Behavior {type: 'Unhealthy Eating'})-[:CONTRIBUTES_TO]->(:Risk {type: 'Global Health Risks'})
    CREATE (:Chemical {type: 'Sodium Chloride'})-[:CONTAINS]->(:Element {type: 'Sodium'})
    CREATE (:ChronicDiseases {type: 'Chronic Diseases'})-[:IS_SUBJECT_TO]->(:DiseasePrevention {type: 'Disease Prevention'})
    CREATE (:Commission {type: 'Childhood Obesity Commission'})-[:FOCUSES_ON]->(:Condition {type: 'Childhood Obesity'})
    CREATE (:Conference {type: 'ICN2'})-[:ADOPTED]->(:Declaration {type: 'Rome Declaration on Nutrition'})
    CREATE (:CreativeCommonsAttributionNonCommercialShareAlike3IGO {type: 'Creative Commons Attribution-NonCommercial-ShareAlike 3.0 IGO'})-[:IS]->(:Licence {type: 'Licence'})
    CREATE (:Declaration {type: 'Rome Declaration on Nutrition'})-[:INCLUDES]->(:Framework {type: 'Framework for Action'})
    CREATE (:Diet {type: 'Balanced Diet'})-[:PREVENTS]->(:Condition {type: 'Chronic Diseases'})
    CREATE (:Diet {type: 'Balanced Diet'})-[:PREVENTS]->(:Condition {type: 'Malnutrition'})
    CREATE (:DietType {type: 'Balanced Diet'})-[:INCLUDES]->(:FoodGroup {type: 'Whole Fruits And Vegetables'})
    CREATE (:DietaryFats {type: 'Dietary Fats'})-[:INCLUDE]->(:MonounsaturatedFats {type: 'Monounsaturated Fats'})
    CREATE (:Document {type: 'Nutrition Guidelines'})-[:CONTAINS]->(:Information {type: 'Nutritional Information'})
    CREATE (:Environment {type: 'Food Environment'})-[:CREATED_BY]->(:Organization {type: 'GovernmentPolicies'})
    CREATE (:Facility {type: 'Health Facility'})-[:LOCATED_IN]->(:Area {type: 'Urban Area'})
    CREATE (:FattyAcid {type: 'Saturated Fatty Acids'})-[:REPLACED_BY]->(:FattyAcid {type: 'Unsaturated Fatty Acids'})
    CREATE (:FattyAcid {type: 'Trans Fatty Acids'})-[:REPLACED_BY]->(:FattyAcid {type: 'Unsaturated Fatty Acids'})
    CREATE (:Food {type: 'Fresh Fruits'})-[:OFTEN_CONSUMED_WITH]->(:Food {type: 'Leafy Greens'})
    CREATE (:Food {type: 'Fresh Fruits'})-[:PART_OF]->(:Diet {type: 'Balanced Diet'})
    CREATE (:Food {type: 'Infant Formula and Solid Foods'})-[:COMPLEMENTS]->(:Food {type: 'Breast Milk'})
    CREATE (:Food {type: 'Leafy Greens'})-[:PART_OF]->(:Diet {type: 'Balanced Diet'})
    CREATE (:Food {type: 'Ultra-Processed Foods'})-[:AFFECTS]->(:Habits {type: 'Eating Habits'})
    CREATE (:Food {type: 'Ultra-Processed Foods'})-[:CONTRIBUTES_TO]->(:Behavior {type: 'Unhealthy Eating'})
    CREATE (:Food {type: 'Whole Foods'})-[:COMPRISES]->(:Diet {type: 'Balanced Diet'})
    CREATE (:Food {type: 'Whole Grain Cereals'})-[:PART_OF]->(:Diet {type: 'Balanced Diet'})
    CREATE (:FreshProduce {type: 'Fresh Produce'})-[:ARE]->(:StarchyRoots {type: 'Starchy Roots'})
    CREATE (:FreshProduce {type: 'Fresh Produce'})-[:PROVIDE]->(:DietaryFibre {type: 'Dietary Fibre'})
    CREATE (:FreshProduce {type: 'Fresh Produce'})-[:REDUCES_RISK_OF]->(:ChronicDiseases {type: 'Chronic Diseases'})
    CREATE (:HealthEducation {type: 'Health Education'})-[:INFLUENCES]->(:EatingHabits {type: 'Eating Habits'})
    CREATE (:Human {type: 'Consumer'})-[:INTERPRETS]->(:Information {type: 'Nutritional Information'})
    CREATE (:HumanMilk {type: 'Human Milk'})-[:COMPLEMENTED_BY]->(:SolidFoods {type: 'Solid Foods'})
    CREATE (:Intake {type: 'Sodium Intake'})-[:AFFECTS]->(:Health {type: 'Population Health'})
    CREATE (:InternationalConference {type: 'International Nutrition Conference'})-[:ASSOCIATED_WITH]->(:Program {type: 'Nutrition Program'})
    CREATE (:Malnutrition {type: 'Malnutrition'})-[:IS_SUBJECT_TO]->(:DiseasePrevention {type: 'Disease Prevention'})
    CREATE (:Model {type: 'Nutrient Profile Model'})-[:USED_BY]->(:Authority {type: 'National Health Authorities'})
    CREATE (:MonounsaturatedFats {type: 'Monounsaturated Fats'})-[:PREFERABLE_TO]->(:SaturatedFats {type: 'Saturated Fats'})
    CREATE (:Nutrient {type: 'Added Sugars'})-[:ADDED_TO]->(:FoodGroup {type: 'Foods And Beverages'})
    CREATE (:Nutrient {type: 'Added Sugars'})-[:CONTRIBUTES_TO]->(:HealthCondition {type: 'Obesity'})
    CREATE (:Nutrient {type: 'Added Sugars'})-[:INCREASES_RISK_OF]->(:HealthCondition {type: 'Tooth Decay'})
    CREATE (:Nutrient {type: 'Dietary Fats'})-[:CONTRIBUTES_TO]->(:EnergyIntake {type: 'Total Daily Energy Intake'})
    CREATE (:Nutrition {type: 'Nutrition'})-[:CONTRIBUTES_TO]->(:ChronicDiseasePrevention {type: 'Chronic Disease Prevention'})
    CREATE (:Nutrition {type: 'Nutrition'})-[:CONTRIBUTES_TO]->(:DiseasePrevention {type: 'Disease Prevention'})
    CREATE (:Nutrition {type: 'Nutrition'})-[:HAS]->(:DietaryMethods {type: 'Dietary Methods'})
    CREATE (:Nutrition {type: 'Nutrition'})-[:IS_PART_OF]->(:HealthEducation {type: 'Health Education'})
    CREATE (:NutritionType {type: 'Breastfeeding'})-[:PART_OF]->(:NutritionType {type: 'Infant Nutrition'})
    CREATE (:Organization {type: 'National Governments'})-[:CREATES]->(:Environment {type: 'Nutrition-Friendly Environment'})
    CREATE (:Organization {type: 'Regional Health Organization'})-[:AFFILIATED_WITH]->(:Agency {type: 'International Health Agency'})
    CREATE (:Organization {type: 'Regional Health Organization'})-[:LOCATED_AT]->(:Facility {type: 'Health Facility'})
    CREATE (:Organization {type: 'WHO Member States'})-[:SETS]->(:Targets {type: 'Global Nutrition Targets'})
    CREATE (:Organization {type: 'WHO'})-[:COLLABORATES_WITH]->(:Organization {type: 'FAO'})
    CREATE (:Organization {type: 'WHO'})-[:DEVELOPED]->(:Plan {type: 'Global NCD Action Plan'})
    CREATE (:Organization {type: 'WHO'})-[:ESTABLISHED]->(:Commission {type: 'Childhood Obesity Commission'})
    CREATE (:Organization {type: 'WHO'})-[:ORGANIZED]->(:Conference {type: 'ICN2'})
    CREATE (:Organization {type: 'WHO'})-[:PUBLISHES]->(:Document {type: 'Nutrition Guidelines'})
    CREATE (:Organization {type: 'World Health Organization'})-[:ADOPTED]->(:Strategy {type: 'Global Strategy On Diet Physical Activity And Health'})
    CREATE (:Organization {type: 'World Health Organization'})-[:ENDORSED]->(:Guideline {type: 'Guidelines On Marketing Of Foods And Non Alcoholic BeveragesToChildren'})
    CREATE (:Organization {type: 'World Health Organization'})-[:MONITORS]->(:Risk {type: 'Global Health Risks'})
    CREATE (:Person {type: 'Dr Ayoub Al Jawaldeh'})-[:CONTACT_EMAIL]->(:Email {type: 'aljawaldeha@who.int'})
    CREATE (:Person {type: 'Dr Ayoub Al Jawaldeh'})-[:IS]->(:Professional {type: 'Nutrition Advisor'})
    CREATE (:Plan {type: 'Global NCD Action Plan'})-[:TARGETS]->(:Disease {type: 'Noncommunicable Diseases'})
    CREATE (:Plan {type: 'Maternal and Child Nutrition Plan'})-[:INCLUDES]->(:Targets {type: 'Global Nutrition Targets'})
    CREATE (:Potassium {type: 'Potassium'})-[:MITIGATES]->(:Sodium {type: 'Sodium'})
    CREATE (:BreastFeeding {type: 'Breastfeeding'})-[:PROMOTES]->(:Nutrition {type: 'Infant Nutrition'})
    CREATE (:BreastFeeding {type: 'Breastfeeding'})-[:FOSTERS]->(:Growth {type: 'Infant Growth'})
    CREATE (:BreastFeeding {type: 'Breastfeeding'})-[:IMPROVES]->(:Development {type: 'Cognitive Development'})
    CREATE (:Professional {type: 'Nutrition Advisor'})-[:PART_OF]->(:Organization {type: 'Regional Health Organization'})
    CREATE (:Salt {type: 'Sodium Chloride'})-[:EQUIVALENT_TO]->(:Sodium {type: 'Sodium'})
    CREATE (:Substance {type: 'Added Sugars'})-[:SHOULD_NOT_BE_ADDED_TO]->(:Food {type: 'Infant Formula and Solid Foods'})
    CREATE (:Substance {type: 'Sodium Chloride'})-[:SHOULD_NOT_BE_ADDED_TO]->(:Food {type: 'Infant Formula and Solid Foods'})
    CREATE (:Targets {type: 'Global Nutrition Targets'})-[:AIMS_TO_ACHIEVE]->(:Indicators {type: 'Child Growth Indicators'})
    CREATE (:TransFattyAcids {type: 'Trans Fatty Acids'})-[:FOUND_IN]->(:UltraProcessedFoods {type: 'Ultra-Processed Foods'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:HAS]->(:RegionalOfficeForTheEasternMediterranean {type: 'Regional Office for the Eastern Mediterranean'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:PUBLISHES]->(:Nutrition {type: 'Nutrition'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:PUBLISHES]->(:NutritionGuidelines {type: 'Nutrition Guidelines'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:PUBLISHES]->(:PublicHealthPublications {type: 'Public Health Publications'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:PUBLISHES]->(:Publications {type: 'Publications'})
$$) AS (a agtype);
