SELECT * FROM create_graph('who_factsheets_part4of4');
SELECT * FROM cypher('who_factsheets_part4of4', $$
    CREATE (:PesticideUse {type: 'Pesticide Use'})-[:PLAYS_A_ROLE_IN]->(:SustainableAgriculture {type: 'Sustainable Agriculture'})
    CREATE (:PesticideUse {type: 'Pesticide Use'})-[:PREVENTS]->(:CropYieldLoss {type: 'Crop Yield Loss'})
    CREATE (:PharmacologicalInterventions {type: 'Pharmacological Interventions'})-[:PROVIDES]->(:PainManagement {type: 'Pain Management'})
    CREATE (:PhysicalActivity {type: 'Physical Activity'})-[:CONTRIBUTES_TO]->(:AnxietyReduction {type: 'Anxiety Reduction'})
    CREATE (:PhysicalActivity {type: 'Physical Activity'})-[:CONTRIBUTES_TO]->(:CancerPrevention {type: 'Cancer Prevention'})
    CREATE (:PhysicalActivity {type: 'Physical Activity'})-[:CONTRIBUTES_TO]->(:ChronicDiseasePrevention {type: 'Chronic Disease Prevention'})
    CREATE (:PhysicalActivity {type: 'Physical Activity'})-[:CONTRIBUTES_TO]->(:SustainableDevelopmentGoals {type: 'Sustainable Development Goals (SDGs)'})
    CREATE (:PhysicalActivity {type: 'Physical Activity'})-[:CONTRIBUTES_TO_ATTAINMENT_OF]->(:GlobalHealthTargets {type: 'Global Health Targets'})
    CREATE (:PhysicalActivity {type: 'Physical Activity'})-[:ENHANCES]->(:MentalHealthOutcomes {type: 'Mental Health Outcomes'})
    CREATE (:PhysicalActivity {type: 'Physical Activity'})-[:IMPROVES]->(:BoneHealth {type: 'Bone Health'})
    CREATE (:PhysicalActivity {type: 'Physical Activity'})-[:IMPROVES]->(:CognitiveFunction {type: 'Cognitive Function'})
    CREATE (:PhysicalActivity {type: 'Physical Activity'})-[:IMPROVES]->(:MuscleStrength {type: 'Muscle Strength'})
    CREATE (:PhysicalActivity {type: 'Physical Activity'})-[:INFLUENCED_BY]->(:EnvironmentalFactor {type: 'Environmental Factors'})
    CREATE (:PhysicalActivity {type: 'Physical Activity'})-[:INFLUENCED_BY]->(:SocioeconomicFactor {type: 'Socioeconomic Factors'})
    CREATE (:PhysicalActivity {type: 'Physical Activity'})-[:OFFERS]->(:HealthBenefit {type: 'Health Benefits'})
    CREATE (:PhysicalActivity {type: 'Physical Activity'})-[:PROVIDES]->(:PhysicalHealthBenefits {type: 'Physical Health Benefits'})
    CREATE (:PhysicalActivity {type: 'Physical Activity'})-[:REDUCES]->(:HealthRisk {type: 'Health Risks'})
    CREATE (:PhysicalActivity {type: 'Physical Activity'})-[:REDUCES]->(:MortalityRate {type: 'Mortality Rate'})
    CREATE (:PhysicalActivity {type: 'Physical Activity'})-[:REDUCES_RISK_OF]->(:CognitiveDeclinePrevention {type: 'Cognitive Decline Prevention'})
    CREATE (:PhysicalActivity {type: 'Physical Activity'})-[:REDUCES_RISK_OF]->(:NonCommunicableDiseases {type: 'Non-Communicable Diseases (NCDs)'})
    CREATE (:PhysicalInactivity {type: 'Physical Inactivity'})-[:INCREASES_RISK_OF]->(:NonCommunicableDisease {type: 'Non-Communicable Diseases'})
    CREATE (:PhysicalInactivity {type: 'Physical Inactivity'})-[:IS_A]->(:GlobalHealthConcern {type: 'Global Health Concern'})
    CREATE (:PhysicalInactivity {type: 'Physical Inactivity'})-[:PLACES_A_BURDEN_ON]->(:HealthcareBurden {type: 'Healthcare Burden'})
    CREATE (:Phytochemicals {type: 'Phytochemicals'})-[:PRESENT_IN]->(:FoodCrops {type: 'FoodCrops'})
    CREATE (:Phytochemicals {type: 'Phytochemicals'})-[:PRODUCE]->(:FoodborneToxins {type: 'Foodborne Toxins'})
    CREATE (:Plan {type: 'Global Action Plan'})-[:TARGETS]->(:Condition {type: 'Noncommunicable Diseases'})
    CREATE (:Plan {type: 'Global Noncommunicable Disease Plan'})-[:SUPPORTS]->(:Prevention {type: 'Chronic Disease Prevention'})
    CREATE (:Plan {type: 'Global Action Plan For Physical Activity'})-[:SETS]->(:Targets {type: 'Physical Activity Targets'})
    CREATE (:Plan {type: 'Maternal And Child Nutrition Plan'})-[:INCLUDES]->(:Goal {type: 'Global Nutrition Goals'})
    CREATE (:Plan {type: 'Noncommunicable Disease Prevention Plan'})-[:INCLUDES]->(:Target {type: 'Global Health Targets'})
    CREATE (:Plan {type: 'Nutrition Action Plan'})-[:GUIDES]->(:Policy {type: 'Nutrition Policy'})
    CREATE (:Plan {type: 'Trans Fat Elimination Plan'})-[:AIMS]->(:Standard {type: 'Food Safety Standard'})
    CREATE (:Plan {type: 'WHO Strategic Plan'})-[:IS_A_PLAN_OF]->(:Organization {type: 'WHO'})
    CREATE (:PlantDerivedToxins {type: 'Plant-Derived Toxins'})-[:IS_A]->(:FoodContaminants {type: 'Food Contaminants'})
    CREATE (:Policy {type: 'Food Marketing Policy'})-[:TARGETS]->(:Field {type: 'Child Nutrition'})
    CREATE (:Policy {type: 'Global Health Policy'})-[:SUPPORTS]->(:Promotion {type: 'Physical Activity Promotion'})
    CREATE (:Policy {type: 'Health Policy'})-[:INCLUDES]->(:Policy {type: 'Cybersecurity Policy'})
    CREATE (:Policy {type: 'Organizational Policies'})-[:COVERS]->(:Concept {type: 'Information Security'})
    CREATE (:Policy {type: 'Organizational Policies'})-[:INCLUDES]->(:Policy {type: 'Cybersecurity Policy'})
    CREATE (:Policy {type: 'Organizational Policies'})-[:INCLUDES]->(:SubPolicy {type: 'Information Security Policy'})
    CREATE (:Policy {type: 'WHO Policies'})-[:INCLUDES]->(:Policy {type: 'Cybersecurity Policy'})
    CREATE (:PolicyRecommendation {type: 'Policy Recommendations'})-[:INCREASES]->(:PhysicalActivityOpportunity {type: 'Physical Activity Opportunities'})
    CREATE (:Pollutant {type: 'Heavy Metals'})-[:POLLUTE]->(:Water {type: 'Water'})
    CREATE (:Pollutant {type: 'Persistent Organic Pollutants (POPs)'})-[:ACCUMULATE_IN]->(:Environment {type: 'Environment'})
    CREATE (:PoorNutrition {type: 'Poor Nutrition'})-[:CONTRIBUTES_TO]->(:ChronicDiseases {type: 'Chronic Diseases'})
    CREATE (:Population {type: 'Pediatric Population'})-[:PARTICULARLY_HARMFUL_TO]->(:Poisoning {type: 'Lead Poisoning'})
    CREATE (:PopulationBasedInterventions {type: 'Population-Based Interventions'})-[:KEY_APPROACH_FOR]->(:CariesPrevention {type: 'Caries Prevention'})
    CREATE (:Practice {type: 'Healthy Eating'})-[:IS_RELATED_TO]->(:Science {type: 'Nutrition Science'})
    CREATE (:Preservative {type: 'Preservatives'})-[:SLOW_DOWN]->(:FoodSpoilage {type: 'Food Spoilage'})
    CREATE (:PreventionStrategy {type: 'Anaemia Prevention'})-[:IS_PART_OF]->(:NutritionPlan {type: 'Maternal Infant And Young Child Nutrition Plan'})
    CREATE (:PreventiveOralHealthIntervention {type: 'Preventive Oral Health Interventions'})-[:INCLUDES]->(:ComprehensiveOralHealthCare {type: 'Comprehensive Oral Health Care'})
    CREATE (:Prion {type: 'Prions'})-[:ASSOCIATED_WITH]->(:NeurodegenerativeDisorder {type: 'Neurodegenerative Disorders'})
    CREATE (:PrivateSector {type: 'Private Sector'})-[:SHOULD_NOT_PREVENT]->(:Intervention {type: 'Evidence-Based Interventions'})
    CREATE (:Procedure {type: 'Early Detection And Screening'})-[:CONTRIBUTES_TO]->(:Concept {type: 'Cancer Control'})
    CREATE (:Procedure {type: 'Surgical Intervention'})-[:TREATS]->(:Disease {type: 'Metastatic Colorectal Carcinoma'})
    CREATE (:Process {type: 'Lactation'})-[:SUPPORTS]->(:Field {type: 'InfantNutrition'})
    CREATE (:Product {type: 'Lead-Based Paint'})-[:IS]->(:Exposure {type: 'Environmental Lead Exposure'})
    CREATE (:Programs {type: 'Capacity Building Programs'})-[:SUPPORTS]->(:Strengthening {type: 'Health System Strengthening'})
    CREATE (:PublicHealthConcern {type: 'Anaemia'})-[:IS]->(:Disease {type: 'Anaemia'})
    CREATE (:PublicHealthEmergency {type: 'Public Health Emergencies'})-[:ARE_DOCUMENTED_IN]->(:SituationReport {type: 'Situation Reports'})
    CREATE (:PublicHealthEmergency {type: 'Public Health Emergencies'})-[:INCLUDES]->(:COVID19Pandemic {type: 'COVID-19 Pandemic'})
    CREATE (:PublicHealthEmergency {type: 'Public Health Emergencies'})-[:INCLUDES]->(:CholeraOutbreak {type: 'Cholera Outbreaks'})
    CREATE (:PublicHealthEmergency {type: 'Public Health Emergencies'})-[:INCLUDES]->(:DiseaseOutbreak {type: 'Disease Outbreaks'})
    CREATE (:PublicHealthEmergency {type: 'Public Health Emergencies'})-[:INCLUDES]->(:Outbreak {type: 'Cholera Outbreaks'})
    CREATE (:PublicHealthEmergency {type: 'Public Health Emergencies'})-[:INCLUDES]->(:Pandemic {type: 'COVID-19 Pandemic'})
    CREATE (:PublicHealthEmergency {type: 'Public Health Emergencies'})-[:INCLUDES]->(:Pandemic {type: 'Pandemics'})
    CREATE (:PublicHealthEmergency {type: 'Public Health Emergencies'})-[:INCLUDE]->(:DiseaseOutbreak {type: 'Disease Outbreaks'})
    CREATE (:PublicHealthEmergency {type: 'Public Health Emergencies'})-[:INVOLVES]->(:DiseaseSurveillance {type: 'Disease Surveillance'})
    CREATE (:PublicHealthObjectives {type: 'Public Health Objectives'})-[:GUIDE]->(:Intervention {type: 'Evidence-Based Interventions'})
    CREATE (:Publication {type: 'Scientific Publications'})-[:INCLUDES]->(:Document {type: 'Fact Sheets'})
    CREATE (:PyrrolizidineAlkaloids {type: 'Pyrrolizidine Alkaloids'})-[:ARE]->(:HepatotoxicAlkaloids {type: 'Hepatotoxic Alkaloids'})
    CREATE (:PyrrolizidineAlkaloids {type: 'Pyrrolizidine Alkaloids'})-[:PRODUCED_BY]->(:WeedContaminants {type: 'Weed Contaminants'})
    CREATE (:PyrrolizidineAlkaloids {type: 'Pyrrolizidine Alkaloids'})-[:ARE]->(:ToxicCompounds {type: 'Toxic Compounds'})
    CREATE (:PyrrolizidineAlkaloids {type: 'Pyrrolizidine Alkaloids'})-[:FOUND_IN]->(:FoodContaminants {type: 'Food Contaminants'})
    CREATE (:Rare {type: 'Hypnatremia'})-[:IS]->(:Condition {type: 'Hypnatremia'})
    CREATE (:ReferenceData {type: 'Growth Reference Data'})-[:APPLIES_TO]->(:NutritionStatus {type: 'Adolescent Nutrition Status'})
    CREATE (:Region {type: 'African Region'})-[:PART_OF]->(:Organization {type: 'WHORegional Offices'})
    CREATE (:Region {type: 'Eastern MediterraneanRegion'})-[:PART_OF]->(:Organization {type: 'WHO Regional Offices'})
    CREATE (:Region {type: 'European Region'})-[:PART_OF]->(:Organization {type: 'WHORegional Offices'})
    CREATE (:Region {type: 'Geographic Regions'})-[:INCLUDES]->(:Region {type: 'Africa Region'})
    CREATE (:Region {type: 'Geographic Regions'})-[:INCLUDES]->(:SubRegion {type: 'African Region'})
    CREATE (:Region {type: 'Geographic Regions'})-[:INCLUDES]->(:SubRegion {type: 'Sub-Saharan Africa'})
    CREATE (:Region {type: 'Region Of The Americas'})-[:PART_OF]->(:Organization {type: 'WHORegional Offices'})
    CREATE (:Region {type: 'South East Asia Region'})-[:PART_OF]->(:Organization {type: 'WHORegional Offices'})
    CREATE (:Region {type: 'Western PacificRegion'})-[:PART_OF]->(:Organization {type: 'WHO Regional Offices'})
    CREATE (:RegionOfTheAmericas {type: 'Region of the Americas'})-[:IS]->(:RegionalHealthOffice {type: 'Regional Health Office'})
    CREATE (:RegionOfTheAmericas {type: 'Region of the Americas'})-[:IS]->(:WHORegionalOffice {type: 'WHO Regional Office'})
    CREATE (:RegionOfTheAmericas {type: 'Region of the Americas'})-[:IS_PART_OF]->(:RegionalHealthOffice {type: 'Regional Health Office'})
    CREATE (:RegionOfTheAmericas {type: 'Region of the Americas'})-[:PART_OF]->(:WorldHealthOrganization {type: 'World Health Organization'})
    CREATE (:RegularPhysicalActivity {type: 'Regular Physical Activity'})-[:ENHANCES]->(:MentalHealth {type: 'Mental Health'})
    CREATE (:RegularPhysicalActivity {type: 'Regular Physical Activity'})-[:IMPROVES]->(:CardiovascularHealth {type: 'Cardiovascular Health'})
    CREATE (:RegularPhysicalActivity {type: 'Regular Physical Activity'})-[:IMPROVES]->(:SleepQuality {type: 'Sleep Quality'})
    CREATE (:RegularPhysicalActivity {type: 'Regular Physical Activity'})-[:REDUCES_RISK_OF]->(:Type2DiabetesPrevention {type: 'Type 2 Diabetes Prevention'})
    CREATE (:Regulation {type: 'International Health Regulations'})-[:INTEGRATES]->(:Safety {type: 'Food Safety'})
    CREATE (:Regulation {type: 'International Health Regulations'})-[:IMPLEMENTED_BY]->(:Organization {type: 'World Health Organization'})
    CREATE (:RegulatoryAgency {type: 'Regulatory Agencies'})-[:MONITORS]->(:FoodSupply {type: 'Food Supply'})
    CREATE (:Rehabilitation2030Initiative {type: 'Rehabilitation 2030 Initiative'})-[:INCLUDES]->(:PackageOfInterventions {type: 'Package of Interventions'})
    CREATE (:RehabilitationTherapies {type: 'Rehabilitation Therapies'})-[:ENHANCES]->(:JointMobility {type: 'Joint Mobility'})
    CREATE (:Report {type: 'Global Health Reports'})-[:INCLUDES]->(:Statistics {type: 'Global Health Statistics'})
    CREATE (:Report {type: 'Health Reports'})-[:INCLUDES]->(:Statistic {type: 'Global Health Statistics'})
    CREATE (:Report {type: 'Sodium Intake Reduction Report'})-[:MONITORS]->(:Progress {type: 'Sodium Reduction Progress'})
    CREATE (:Report {type: 'TechnicalReports'})-[:INCLUDES]->(:Statistics {type: 'GlobalHealthStatistics'})
    CREATE (:ReproductiveHealth {type: 'Reproductive Health'})-[:IS]->(:ChronicConditions {type: 'Chronic Conditions'})
    CREATE (:ResearchInstitution {type: 'Global Health Metrics'})-[:PUBLISHED_RESEARCH_ON]->(:HealthIndicator {type: 'Anaemia Prevalence'})
    CREATE (:ResearchStudy {type: 'Global Burden of Disease Study'})-[:ANALYZES]->(:RiskFactors {type: 'Risk Factors for Non-Communicable Diseases'})
    CREATE (:ResistanceTraining {type: 'Resistance Training'})-[:OFFERS]->(:HealthBenefit {type: 'Health Benefits'})
    CREATE (:Resource {type: 'Health Resources'})-[:INCLUDES]->(:Material {type: 'Health Education Materials'})
    CREATE (:Resource {type: 'Information Resources'})-[:COVERS]->(:Topic {type: 'Electronic Waste'})
    CREATE (:RiskManagementStrategies {type: 'Risk Management Strategies'})-[:PREVENT]->(:FoodContamination {type: 'Food Contamination'})
    CREATE (:RiskManagementStrategy {type: 'Risk Management Strategies'})-[:PREVENTS]->(:FoodContamination {type: 'Food Contamination'})
    CREATE (:RuminantTransFattyAcids {type: 'Ruminant Trans Fatty Acids'})-[:CAN_BE_FOUND_IN]->(:DairyProducts {type: 'Dairy Products'})
    CREATE (:RuminantTransFattyAcids {type: 'Ruminant Trans Fatty Acids'})-[:CAN_BE_FOUND_IN]->(:RedMeat {type: 'Red Meat'})
    CREATE (:SafeFoodHandlingPractices {type: 'Safe Food Handling Practices'})-[:INCLUDES]->(:ProperCooking {type: 'Proper Cooking'})
    CREATE (:SaturatedFat {type: 'Saturated Fat'})-[:SHOULD_BE_LESS_THAN_10_PERCENT_OF]->(:DailyEnergyIntake {type: 'Daily Energy Intake'})
    CREATE (:Screening)-[:COMPLEMENTARY_TO]->(:EarlyDiagnosis)
    CREATE (:Screening)-[:INCLUDES]->(:HPVTesting)
    CREATE (:SedentaryBehavior {type: 'Sedentary Behavior'})-[:CONTRIBUTES_TO]->(:ProlongedScreenTime {type: 'Prolonged Screen Time'})
    CREATE (:SedentaryBehaviour {type: 'Sedentary Behaviour'})-[:ASSOCIATED_WITH]->(:AdverseHealthOutcomes {type: 'Adverse Health Outcomes'})
    CREATE (:SedentaryBehaviour {type: 'Sedentary Behaviour'})-[:INCREASES]->(:HealthRisk {type: 'Health Risks'})
    CREATE (:SedentaryBehaviour {type: 'Sedentary Behaviour'})-[:INCREASES_RISK_OF]->(:Depression {type: 'Depression'})
    CREATE (:SedentaryLifestyle {type: 'Sedentary Lifestyle'})-[:INCREASES]->(:HealthRisks {type: 'Health Risks'})
    CREATE (:SedentaryLifestyle {type: 'Sedentary Lifestyle'})-[:INCREASES_RISK_OF]->(:CardiovascularDisease {type: 'Cardiovascular Disease'})
    CREATE (:SedentaryLifestyle {type: 'Sedentary Lifestyle'})-[:INCREASES_RISK_OF]->(:CognitiveImpairment {type: 'Cognitive Impairment'})
    CREATE (:Sequencing {type: 'Whole Genome Sequencing'})-[:SUPPORTS]->(:Surveillance {type: 'Foodborne Disease Surveillance'})
    CREATE (:SexuallyTransmittedInfections {type: 'Sexually Transmitted Infections'})-[:IS]->(:InfectiousDiseases {type: 'Infectious Diseases'})
    CREATE (:SocioEnvironmentalFactors {type: 'Socio-Environmental Factors'})-[:INFLUENCES]->(:PersonalFoodChoices {type: 'Personal Food Choices'})
    CREATE (:SocioeconomicDisadvantage {type: 'Socioeconomic Disadvantage'})-[:LINKED_WITH]->(:NonCommunicableDisease {type: 'Non-Communicable Diseases'})
    CREATE (:SocioeconomicDisadvantage)-[:LINKED_WITH]->(:NonCommunicableDisease)
    CREATE (:SodiumIntake {type: 'Sodium Intake'})-[:CONTRIBUTES_TO]->(:Hypertension {type: 'Hypertension'})
    CREATE (:SouthEastAsiaRegion {type: 'South-East Asia Region'})-[:IS]->(:RegionalHealthOffice {type: 'Regional Health Office'})
    CREATE (:SouthEastAsiaRegion {type: 'South-East Asia Region'})-[:IS]->(:WHORegionalOffice {type: 'WHO Regional Office'})
    CREATE (:SouthEastAsiaRegion {type: 'South-East Asia Region'})-[:IS_PART_OF]->(:RegionalHealthOffice {type: 'Regional Health Office'})
    CREATE (:SouthEastAsiaRegion {type: 'South-East Asia Region'})-[:PART_OF]->(:WorldHealthOrganization {type: 'World Health Organization'})
    CREATE (:Species {type: 'Salmonella bongori'})-[:SPECIES_OF]->(:Bacteria {type: 'Salmonella'})
    CREATE (:Species {type: 'Salmonella enterica'})-[:SPECIES_OF]->(:Bacteria {type: 'Salmonella'})
    CREATE (:Standard {type: 'Child Growth Standards'})-[:APPLIES_TO]->(:NutritionStatus {type: 'Pediatric Nutrition Status'})
    CREATE (:Standard {type: 'Codex Alimentarius'})-[:PROVIDES]->(:Standard {type: 'Food Standards'})
    CREATE (:Strategy {type: 'Global Anaemia Strategy'})-[:AIMS_TO_PREVENT_DIAGNOSE_AND_MANAGE]->(:Disease {type: 'Iron Deficiency Anaemia'})
    CREATE (:Strategy {type: 'Global Anaemia Strategy'})-[:IMPLEMENTED_AT]->(:Location {type: 'National Level'})
    CREATE (:Strategy {type: 'Global Food Safety Strategy'})-[:SUPPORTS]->(:System {type: 'Food Safety Systems'})
    CREATE (:Strategy {type: 'Global NCD Action Plan'})-[:AIMS_AT]->(:Goal {type: 'NCD Prevention and Control'})
    CREATE (:Strategy {type: 'Global Nutrition Strategy'})-[:PROMOTES]->(:Patterns {type: 'Healthy Eating Patterns'})
    CREATE (:Strategy {type: 'Global Strategy on Diet, Physical Activity and Health'})-[:DEVELOPED_BY]->(:Organization {type: 'World Health Organization (WHO)'})
    CREATE (:Strategy {type: 'Sodium Reduction Strategies'})-[:CONTRIBUTES_TO]->(:Prevention {type: 'Chronic Disease Prevention'})
    CREATE (:Strategy {type: 'World Health Organization Strategies'})-[:INVOLVES]->(:Concept {type: 'Cancer Prevention And Control'})
    CREATE (:Study {type: 'Global Burden Of Disease Study'})-[:PUBLISHED_DATA_ON]->(:Condition {type: 'Anaemia Prevalence'})
    CREATE (:Study {type: 'Global Burden of Disease Study'})-[:COLLABORATED_WITH]->(:Group {type: 'Vision Loss Expert Group'})
    CREATE (:Study {type: 'Global Burden of Disease Study'})-[:CONDUCTED_BY]->(:Organization {type: 'Institute for Health Metrics and Evaluation'})
    CREATE (:Stunting {type: 'Stunting'})-[:ASSOCIATED_WITH]->(:PoorMaternalNutrition {type: 'Poor Maternal Nutrition'})
    CREATE (:Substance {type: 'Added Sugars'})-[:HAS]->(:Outcome {type: 'Diet Related Health Outcomes'})
    CREATE (:Substance {type: 'Added Sugars'})-[:INCREASES]->(:Disease {type: 'Cardiometabolic Disease'})
    CREATE (:Substance {type: 'Dietary Trans Fatty Acids'})-[:HAS]->(:Alternative {type: 'Healthier Alternatives'})
    CREATE (:Substance {type: 'Dietary Trans Fatty Acids'})-[:LEADS_TO]->(:Disease {type: 'Cardiovascular Disease'})
    CREATE (:Substance {type: 'Lead'})-[:HAS_CONCENTRATION]->(:BloodLeadLevels {type: 'Blood Lead Levels'})
    CREATE (:Substance {type: 'Mycotoxins'})-[:THREAT_TO]->(:Concept {type: 'Food Safety'})
    CREATE (:Substance {type: 'Saturated Fatty Acids'})-[:RELATED_TO]->(:Substance {type: 'Trans Fatty Acids'})
    CREATE (:Substance {type: 'Sodium Intake'})-[:CONTRIBUTES_TO]->(:Disease {type: 'Cardiovascular Disease'})
    CREATE (:SubstanceAbuse {type: 'Substance Abuse'})-[:CAUSES]->(:MortalityRate {type: 'Mortality Rate'})
    CREATE (:SugarSweetenedBeverages {type: 'Sugar-Sweetened Beverages'})-[:CONTRIBUTES_TO_THE_BURDEN_OF]->(:OralHealthDisorders {type: 'Oral Health Disorders'})
    CREATE (:SugarSweetenedBeverages {type: 'Sugar-Sweetened Beverages'})-[:SOURCE_OF]->(:AddedSugars {type: 'Added Sugars'})
    CREATE (:SugarTaxation {type: 'Sugar Taxation'})-[:AIMS_TO]->(:DentalCariesPrevention {type: 'Dental Caries Prevention'})
    CREATE (:Supplement {type: 'Zinc Supplementation'})-[:SUPPLEMENTS_TREATMENT_OF]->(:Disease {type: 'Diarrheal Disease'})
    CREATE (:SupportiveEnvironments {type: 'Supportive Environments'})-[:FOSTERS]->(:HealthyLifestyleBehaviors {type: 'Healthy Lifestyle Behaviors'})
    CREATE (:SustainableDevelopmentGoal2 {type: 'Sustainable Development Goal 2 (SDG 2)'})-[:AIMS_TO_ACHIEVE]->(:ZeroHunger {type: 'Zero Hunger'})
    CREATE (:SustainableDevelopmentGoal35 {type: 'Sustainable Development Goal 3.5'})-[:INCLUDES]->(:SubstanceAbusePreventionAndTreatment {type: 'Substance Abuse Prevention and Treatment'})
    CREATE (:Target {type: 'Global Health Targets'})-[:AIMS]->(:Outcome {type: 'Sodium Reduction'})
    CREATE (:Targets {type: 'Physical Activity Targets'})-[:AIMS_FOR]->(:Goals {type: 'Physical Inactivity Reduction Goals'})
    CREATE (:Therapy {type: 'Chemotherapy Regimens'})-[:INDUCES_CELL_DEATH]->(:Cell {type: 'Neoplastic Cells'})
    CREATE (:Therapy {type: 'Insulin Therapy'})-[:IS_A_NECESSARY_TREATMENT_FOR]->(:Disease {type: 'Type 1 Diabetes Management'})
    CREATE (:Therapy {type: 'Locoregional Therapies'})-[:TREATS]->(:Disease {type: 'Metastatic Disease'})
    CREATE (:Therapy {type: 'Molecular Targeted Therapy'})-[:USED_IN_COMBINATION_WITH]->(:Therapy {type: 'Chemotherapy Regimens'})
    CREATE (:Therapy {type: 'Oral Rehydration Therapy'})-[:TREATS]->(:Disease {type: 'Diarrheal Disease'})
    CREATE (:Therapy {type: 'Radiation Oncology'})-[:MANAGES]->(:Symptom {type: 'Symptomatology'})
    CREATE (:Therapy {type: 'Renal Replacement Therapy'})-[:CAN_BE_DEVELOPED_FOR]->(:Setting {type: 'Resource-Constrained Settings'})
    CREATE (:Therapy {type: 'Therapy'})-[:INCLUDES]->(:ElectrolyteReplacement {type: 'Electrolyte Replacement'})
    CREATE (:Therapy)-[:MAY_INCLUDE]->(:SurgicalIntervention)
    CREATE (:TobaccoSmoking {type: 'Tobacco Smoking'})-[:INCREASES_RISK_OF]->(:Carcinoma {type: 'Carcinoma'})
    CREATE (:TobaccoSmoking {type: 'Tobacco Smoking'})-[:INCREASES_RISK_OF]->(:NonCommunicableDisease {type: 'Non-Communicable Diseases'})
    CREATE (:Tool {type: 'Data Visualization Tools'})-[:INCLUDES]->(:Dashboard {type: 'Pandemic Surveillance Dashboard'})
    CREATE (:Tool {type: 'Data Visualization Tools'})-[:INCLUDES]->(:Dashboard {type: 'Progress Tracking Dashboards'})
    CREATE (:Tool {type: 'Food Safety Assessment Tool'})-[:ASSESSS]->(:System {type: 'Food Safety Systems'})
    CREATE (:Tool {type: 'Nutrient Profiling'})-[:GUIDES]->(:Policy {type: 'National Nutrition Policy'})
    CREATE (:Tool {type: 'Sodium Reduction Monitoring Tool'})-[:MONITORS]->(:Progress {type: 'Sodium Reduction Progress'})
    CREATE (:ToothDecay {type: 'Tooth Decay'})-[:ALSO_KNOWN_AS]->(:DentalCaries {type: 'Dental Caries'})
    CREATE (:ToothDecay {type: 'Tooth Decay'})-[:ASSOCIATED_WITH]->(:SocioeconomicDisadvantage {type: 'Socioeconomic Disadvantage'})
    CREATE (:ToothDecay {type: 'Tooth Decay'})-[:DISPROPORTIONATELY_AFFECTS]->(:SocioeconomicallyDisadvantagedPopulations {type: 'Socioeconomically Disadvantaged Populations'})
    CREATE (:ToothDecay {type: 'Tooth Decay'})-[:IS]->(:NonCommunicableDisease {type: 'Non-Communicable Disease'})
    CREATE (:ToothDecay {type: 'Tooth Decay'})-[:IS]->(:PublicHealthConcern {type: 'Public Health Concern'})
    CREATE (:ToothDecay {type: 'Tooth Decay'})-[:OFTEN_NOT_PRIORITIZED_IN]->(:PublicHealthPlanning {type: 'Public Health Planning'})
    CREATE (:Topic {type: 'Electronic Waste'})-[:IS_ALSO_KNOWN_AS]->(:Topic {type: 'Electronic Waste'})
    CREATE (:Topic {type: 'Health Topics'})-[:COVERS]->(:Organization {type: 'World Health Organization'})
    CREATE (:ToxicSubstance {type: 'Lead'})-[:IS]->(:Substance {type: 'Toxic Substance'})
    CREATE (:ToxicSubstance {type: 'Toxic Substances'})-[:CONTAMINATE]->(:FoodProduct {type: 'Food Products'})
    CREATE (:ToxicSubstance {type: 'Toxic Substances'})-[:POSE_RISK_TO]->(:HumanHealth {type: 'Human Health'})
    CREATE (:Toxin {type: 'Mycotoxins'})-[:PRODUCED_BY_MOULD_ON]->(:Cereal {type: 'Cereals'})
    CREATE (:TrackingTool {type: 'Country Score Card'})-[:TRACKS]->(:Progress {type: 'National Progress In Dietary Trans Fat Elimination'})
    CREATE (:TransFattyAcid {type: 'Trans Fatty Acids (TFAs)'})-[:CAN_COME_FROM]->(:IndustrialFoodProcessing {type: 'Industrial Food Processing'})
    CREATE (:TransFattyAcid {type: 'Trans Fatty Acids (TFAs)'})-[:CAN_COME_FROM]->(:RuminantAnimals {type: 'Ruminant Animals'})
    CREATE (:TransFattyAcid {type: 'Trans Fatty Acids (TFAs)'})-[:INCREASES_THE_RISK_OF]->(:CardiovascularDisease {type: 'Cardiovascular Disease'})
    CREATE (:TransFattyAcid {type: 'Trans Fatty Acids (TFAs)'})-[:IS_A_TYPE_OF]->(:UnsaturatedFattyAcid {type: 'Unsaturated Fatty Acids'})
    CREATE (:Trial {type: 'Clinical Trials'})-[:PROVIDES_ACCESS_TO]->(:Therapy {type: 'Investigational Therapies'})
    CREATE (:UNDecadeOfHealthyAgeing {type: 'UN Decade of Healthy Ageing'})-[:PROMOTES]->(:HealthSystemReorientation {type: 'Health System Reorientation'})
    CREATE (:UltraProcessedFoods {type: 'Ultra Processed Foods'})-[:HAS]->(:Nutrient {type: 'High Sodium Content'})
    CREATE (:Undernutrition {type: 'Undernutrition'})-[:INCLUDES]->(:AcuteMalnutrition {type: 'Acute Malnutrition'})
    CREATE (:Undernutrition {type: 'Undernutrition'})-[:INCLUDES]->(:ChronicMalnutrition {type: 'Chronic Malnutrition'})
    CREATE (:Undernutrition {type: 'Undernutrition'})-[:INCLUDES]->(:GrowthRestriction {type: 'Growth Restriction'})
    CREATE (:Undernutrition {type: 'Undernutrition'})-[:INCLUDES]->(:LowBirthWeight {type: 'Low Birth Weight'})
    CREATE (:Undernutrition {type: 'Undernutrition'})-[:INCLUDES]->(:Stunting {type: 'Stunting'})
    CREATE (:Undernutrition {type: 'Undernutrition'})-[:INCLUDES]->(:Underweight {type: 'Underweight'})
    CREATE (:Undernutrition {type: 'Undernutrition'})-[:INCLUDES]->(:Wasting {type: 'Wasting'})
    CREATE (:UnhealthyDietaryPattern {type: 'Unhealthy Dietary Patterns'})-[:LINKED_TO]->(:PoorNutritionalStatus {type: 'Poor Nutritional Status'})
    CREATE (:UnhealthyDietaryPattern {type: 'Unhealthy Dietary Patterns'})-[:LINKED_WITH]->(:PoorNutritionalStatus {type: 'Poor Nutritional Status'})
    CREATE (:UnhealthyDietaryPattern {type: 'Unhealthy Dietary Patterns'})-[:RISK_FACTOR_FOR]->(:NoncommunicableDisease {type: 'Noncommunicable Diseases (NCDs)'})
    CREATE (:UnhealthyEating {type: 'Unhealthy Eating'})-[:INCREASES_RISK_OF]->(:NonCommunicableDisease {type: 'Non-Communicable Diseases'})
    CREATE (:UnitedNationsDecadeOfActionOnNutrition {type: 'United Nations Decade of Action on Nutrition'})-[:AIMS_TO_ACHIEVE]->(:GlobalNutritionTarget {type: 'Global Nutrition Targets'})
    CREATE (:UnitedNationsDecadeOfActionOnNutrition {type: 'United Nations Decade of Action on Nutrition'})-[:ALIGNS_WITH]->(:SustainableDevelopmentGoal2 {type: 'Sustainable Development Goal 2 (Zero Hunger)'})
    CREATE (:UnitedNationsFoodAndAgricultureOrganization {type: 'United Nations Food and Agriculture Organization (FAO)'})-[:ESTIMATES]->(:FoodSecurity {type: 'Food Security'})
    CREATE (:UniversalHealthCoverage {type: 'Universal Health Coverage'})-[:REQUIRES]->(:AlcoholUseDisorders {type: 'Alcohol Use Disorders'})
    CREATE (:VectorBorneDiseases {type: 'Vector-Borne Diseases'})-[:IS]->(:InfectiousDiseases {type: 'Infectious Diseases'})
    CREATE (:Visualization {type: 'Health Data Visualization'})-[:INCLUDES]->(:Surveillance {type: 'COVID-19 Surveillance'})
    CREATE (:Vitamin {type: 'Ascorbic Acid'})-[:ENHANCES]->(:Process {type: 'Iron Absorption'})
    CREATE (:Vitamin {type: 'Cobalamin'})-[:CONTRIBUTES_TO_SYNTHESIS_OF]->(:Protein {type: 'Haemoglobin'})
    CREATE (:Vitamin {type: 'Folic Acid'})-[:CONTRIBUTES_TO_SYNTHESIS_OF]->(:Protein {type: 'Haemoglobin'})
    CREATE (:Vitamin {type: 'Retinol'})-[:CONTRIBUTES_TO_SYNTHESIS_OF]->(:Protein {type: 'Haemoglobin'})
    CREATE (:Vitamin {type: 'Riboflavin'})-[:CONTRIBUTES_TO_SYNTHESIS_OF]->(:Protein {type: 'Haemoglobin'})
    CREATE (:VulnerablePopulation)-[:EXPOSED_TO]->(:HealthRisk)
    CREATE (:VulnerablePopulations {type: 'Vulnerable Populations'})-[:MAY_REQUIRE]->(:AntimicrobialTherapy {type: 'Antimicrobial Therapy'})
    CREATE (:WHO {type: 'WHO'})-[:CONVENES]->(:JECFA {type: 'JECFA'})
    CREATE (:WHOGlobalAlcoholActionPlan {type: 'WHO Global Alcohol Action Plan'})-[:AIMS_TO]->(:ReducingHarmfulAlcoholUse {type: 'Reducing Harmful Alcohol Use'})
    CREATE (:WHOGlobalBreastCancerInitiative)-[:IMPROVES]->(:BreastCancerControl)
    CREATE (:Wasting {type: 'Wasting'})-[:CAUSED_BY]->(:InfectiousDiseases {type: 'Infectious Diseases'})
    CREATE (:Water {type: 'Safe Drinking Water'})-[:PREVENTS]->(:Disease {type: 'Diarrheal Disease'})
    CREATE (:WaterPollution {type: 'Water Pollution'})-[:CONTAMINATES]->(:ToxicSubstance {type: 'Lead'})
    CREATE (:WeightManagement {type: 'Weight Management'})-[:SUPPORTS]->(:SymptomManagement {type: 'Symptom Management'})
    CREATE (:WesternPacificRegion {type: 'Western Pacific Region'})-[:IS]->(:RegionalHealthOffice {type: 'Regional Health Office'})
    CREATE (:WesternPacificRegion {type: 'Western Pacific Region'})-[:IS]->(:WHORegionalOffice {type: 'WHO Regional Office'})
    CREATE (:WesternPacificRegion {type: 'Western Pacific Region'})-[:IS_PART_OF]->(:RegionalHealthOffice {type: 'Regional Health Office'})
    CREATE (:WesternPacificRegion {type: 'Western Pacific Region'})-[:PART_OF]->(:WorldHealthOrganization {type: 'World Health Organization'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization (WHO)'})-[:ASSESS_HEALTH_RISKS]->(:PesticideUse {type: 'Pesticide Use'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization (WHO)'})-[:COLLABORATES_WITH]->(:UnitedNationsFoodAndAgricultureOrganization {type: 'United Nations Food and Agriculture Organization (FAO)'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization (WHO)'})-[:DEVELOPS]->(:GlobalNutritionStrategy {type: 'Global Nutrition Strategy'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization (WHO)'})-[:LEADS]->(:UnitedNationsDecadeOfActionOnNutrition {type: 'United Nations Decade of Action on Nutrition'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization (WHO)'})-[:PROVIDES]->(:PhysicalActivityGuidelines {type: 'Physical Activity Guidelines'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:ADVOCATES_FOR]->(:FoodSafety {type: 'Food Safety'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:AIMS_TO_REDUCE_SODIUM_INTAKE_OF_BY_30_PERCENT_BY_2025]->(:GlobalPopulation {type: 'Global Population'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:ASSESS_THE_RISKS_TO_HUMAN_HEALTH_FROM]->(:FoodAdditive {type: 'Food Additives'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:COLLABORATE_WITH]->(:FoodAndAgricultureOrganization {type: 'Food and Agriculture Organization'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:CONDUCTS]->(:DiseaseSurveillance {type: 'Disease Surveillance'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:CONDUCTS]->(:EpidemiologicalSurveillance {type: 'Epidemiological Surveillance'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:CONDUCTS]->(:HealthRiskAssessment {type: 'Health Risk Assessment'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:DIVIDED_INTO]->(:GeographicRegions {type: 'Geographic Regions'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:ENDORSES]->(:GlobalNutritionTargets {type: 'Global Nutrition Targets'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:HAS]->(:RegionalHealthOffices {type: 'Regional Health Offices'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:LAUNCHES]->(:RehabilitationInitiative {type: 'Rehabilitation Initiative'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:MAINTAINS]->(:CountryOffice {type: 'Country Offices'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:OPERATES_IN]->(:Country {type: 'Countries'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:OPERATES_IN]->(:GeographicLocation {type: 'Geographic Locations'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:PROVIDES_INFORMATION_ON]->(:FoodSafety {type: 'Food Safety'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:RESPONDS_TO]->(:PublicHealthEmergency {type: 'Public Health Emergencies'})
    CREATE (:WorldHealthOrganization {type: 'World Health Organization'})-[:WORKS_ON]->(:DentalCariesPreventionPolicies {type: 'Dental Caries Prevention Policies'})
    CREATE (:WorldHealthOrganization)-[:ESTABLISHES]->(:MaximumResidueLimits)
    CREATE (:WorldHealthOrganization)-[:LEADS]->(:GlobalNonCommunicableDiseasePrevention)
    CREATE (:WorldHealthOrganization)-[:PROMOTES]->(:CancerPrevention)
    CREATE (:ZoonoticDiseases {type: 'Zoonotic Diseases'})-[:IS]->(:InfectiousDiseases {type: 'Infectious Diseases'})
    CREATE (:ZoonoticHosts {type: 'Zoonotic Hosts'})-[:SHOW]->(:Salmonellosis {type: 'Salmonellosis'})
$$) AS (a agtype);
