SELECT * FROM create_graph('food_safety');
SELECT * FROM cypher('food_safety', $$
    CREATE (:Alliance {type: 'FoodSafetyAlliance'})-[:TAKES]->(:Approach {type: 'OneHealthApproach'})
    CREATE (:AntimicrobialAgents {type: 'Antimicrobial Agents'})-[:TREATS]->(:BacterialInfections {type: 'Bacterial Infections'})
    CREATE (:BacterialPathogens {type: 'Bacterial Pathogens'})-[:CAUSES]->(:FoodborneIllnesses {type: 'Foodborne Illnesses'})
    CREATE (:Change {type: 'Climate Change'})-[:INCREASES]->(:Risk {type: 'Foodborne Disease Risk'})
    CREATE (:FoodSafety {type: 'Food Safety'})-[:IS_A_SHARED_RESPONSIBILITY_AMONG]->(:Consumers {type: 'Consumers'})
    CREATE (:FoodSafety {type: 'Food Safety'})-[:IS_A_SHARED_RESPONSIBILITY_AMONG]->(:FoodManufacturers {type: 'Food Manufacturers'})
    CREATE (:FoodSafety {type: 'Food Safety'})-[:IS_A_SHARED_RESPONSIBILITY_AMONG]->(:Governments {type: 'Governments'})
    CREATE (:FoodSafety {type: 'Food Safety'})-[:IS_LINKED_TO]->(:FoodSecurity {type: 'Food Security'})
    CREATE (:FoodSafety {type: 'Food Safety'})-[:IS_LINKED_TO]->(:Nutrition {type: 'Nutrition'})
    CREATE (:FoodborneIllnesses {type: 'Foodborne Illnesses'})-[:HARMS]->(:NationalEconomies {type: 'National Economies'})
    CREATE (:FoodborneIllnesses {type: 'Foodborne Illnesses'})-[:STRAINS]->(:HealthcareSystems {type: 'Healthcare Systems'})
    CREATE (:Guideline {type: 'WHO Five Keys'})-[:GUIDES]->(:Practice {type: 'Safe Food Handling Practices'})
    CREATE (:Guidelines {type: 'SafeFoodHandlingGuidelines'})-[:PROMOTES]->(:Practices {type: 'FoodSafetyPractices'})
    CREATE (:Illness {type: 'Foodborne Illnesses'})-[:AFFECTS]->(:Health {type: 'Public Health'})
    CREATE (:Listeria {type: 'Listeria'})-[:CAUSES]->(:FoodborneInfections {type: 'Foodborne Infections'})
    CREATE (:Manufacturer {type: 'Food Manufacturers'})-[:RESPONSIBLE_FOR]->(:Safety {type: 'Food Safety'})
    CREATE (:Metal {type: 'Heavy Metals'})-[:CAUSES]->(:Pollution {type: 'Environmental Pollution'})
    CREATE (:Network {type: 'InternationalFoodSafetyNetwork'})-[:RESPONDS_TO]->(:Emergencies {type: 'FoodSafetyEmergencies'})
    CREATE (:Norovirus {type: 'Norovirus'})-[:CAUSES]->(:FoodborneInfections {type: 'Foodborne Infections'})
    CREATE (:Organization {type: 'World Health Organization'})-[:COLLABORATES_WITH]->(:Agencies {type: 'United Nations Food Agencies'})
    CREATE (:Organization {type: 'World Health Organization'})-[:STRENGTHENS]->(:Governance {type: 'Food Safety Governance'})
    CREATE (:Pollutant {type: 'Dioxins'})-[:BY_PRODUCT_OF]->(:Emissions {type: 'Industrial Emissions'})
    CREATE (:Prion {type: 'Prions'})-[:ASSOCIATED_WITH]->(:Tissue {type: 'Neural Tissue'})
    CREATE (:Prions {type: 'Prions'})-[:IS_ASSOCIATED_WITH]->(:NeurodegenerativeDiseases {type: 'Neurodegenerative Diseases'})
    CREATE (:Regulations {type: 'International Health Regulations'})-[:INTEGRATES]->(:Policy {type: 'Food Safety Policy'})
    CREATE (:Safety {type: 'Food Safety'})-[:IMPACTED_BY]->(:System {type: 'Global Food Systems'})
    CREATE (:Safety {type: 'Food Safety'})-[:REQUIRES]->(:Collaboration {type: 'Intersectoral Collaboration'})
    CREATE (:Salmonella {type: 'Salmonella'})-[:IS_A_TYPE_OF]->(:BacterialPathogens {type: 'Bacterial Pathogens'})
    CREATE (:Sequencing {type: 'Whole Genome Sequencing'})-[:SUPPORTS]->(:Surveillance {type: 'Foodborne Disease Surveillance'})
    CREATE (:Standard {type: 'Codex Alimentarius'})-[:FORMS_BASIS_FOR]->(:Standards {type: 'Food Standards'})
    CREATE (:Strategy {type: 'Global Food Safety Strategy'})-[:SUPPORTS]->(:Governance {type: 'Food Safety Governance'})
    CREATE (:Tool {type: 'Food Safety Assessment Tool'})-[:ASSESSS]->(:Governance {type: 'Food Safety Governance'})
    CREATE (:Toxin {type: 'Mycotoxins'})-[:PRODUCED_BY]->(:Contamination {type: 'Fungal Contamination'})
$$) AS (a agtype);
