SELECT * FROM create_graph('who_factsheets_part2of4');
SELECT * FROM cypher('who_factsheets_part2of4', $$
    CREATE (:Disease {type: 'Dengue Fever'})-[:IS_A]->(:Topic {type: 'Health Topics'})
    CREATE (:Disease {type: 'Diabetes Mellitus'})-[: IS_A]->(:Disease {type: 'Chronic Disease'})
    CREATE (:Disease {type: 'Diabetes Mellitus'})-[:CAUSES]->(:Condition {type: 'Peripheral Neuropathy'})
    CREATE (:Disease {type: 'Diabetes Mellitus'})-[:CAUSES]->(:Disease {type: 'Vascular Disease'})
    CREATE (:Disease {type: 'Diabetes Mellitus'})-[:INCREASES_RISK_OF]->(:Disease {type: 'Chronic Kidney Disease'})
    CREATE (:Disease {type: 'Diabetes Mellitus'})-[:INCREASES_RISK_OF]->(:Disease {type: 'Myocardial Infarction'})
    CREATE (:Disease {type: 'Diabetes Mellitus'})-[:REGULATED_BY]->(:Hormone {type: 'Insulin'})
    CREATE (:Disease {type: 'Diabetes'})-[:ASSOCIATED_WITH]->(:Disease {type: 'Cardiovascular Disease'})
    CREATE (:Disease {type: 'Diarrheal Disease'})-[:AFFECTS]->(:Population {type: 'Pediatric Population'})
    CREATE (:Disease {type: 'Diarrheal Disease'})-[:CAUSES]->(:Condition {type: 'Protein Energy Malnutrition'})
    CREATE (:Disease {type: 'Diarrheal Disease'})-[:CAUSES]->(:Mortality {type: 'Mortality'})
    CREATE (:Disease {type: 'Diarrheal Disease'})-[:LEADS_TO]->(:Condition {type: 'Dehydration'})
    CREATE (:Disease {type: 'Diarrheal Disease'})-[:RESULT_OF]->(:Infection {type: 'Gastrointestinal Infection'})
    CREATE (:Disease {type: 'Diarrheal Diseases'})-[:CAUSES]->(:Outcome {type: 'Preventable Deaths'})
    CREATE (:Disease {type: 'Early Stage Colorectal Cancer'})-[:IS_TREATED_WITH]->(:MedicalProcedure {type: 'Surgical Resection'})
    CREATE (:Disease {type: 'Gestational Diabetes Mellitus'})-[:IS_A_TYPE_OF]->(:Disease {type: 'Diabetes Mellitus'})
    CREATE (:Disease {type: 'Human Immunodeficiency Virus'})-[:CAN_CAUSE]->(:Condition {type: 'Anaemia'})
    CREATE (:Disease {type: 'Impaired Fasting Glucose'})-[:IS_A_PRECURSOR_TO]->(:Disease {type: 'Diabetes Mellitus'})
    CREATE (:Disease {type: 'Impaired Glucose Regulation'})-[:IS_A_PRECURSOR_TO]->(:Disease {type: 'Diabetes Mellitus'})
    CREATE (:Disease {type: 'Infectious Diseases'})-[:CAN_CAUSE]->(:Condition {type: 'Anaemia'})
    CREATE (:Disease {type: 'Iron Deficiency Anaemia'})-[:IS_INCLUDED_IN]->(:GlobalTarget {type: 'Global Nutrition Targets'})
    CREATE (:Disease {type: 'Malaria'})-[:CAN_CAUSE]->(:Condition {type: 'Anaemia'})
    CREATE (:Disease {type: 'Neoplasms'})-[:INCLUDES]->(:Disease {type: 'Colorectal Neoplasms'})
    CREATE (:Disease {type: 'Noncommunicable Diseases (NCDs)'})-[:ASSOCIATED_WITH]->(:Disorder {type: 'Obesity'})
    CREATE (:Disease {type: 'Obesity'})-[:AFFECTS]->(:HealthCondition {type: 'Osteoporosis'})
    CREATE (:Disease {type: 'Obesity'})-[:AFFECTS]->(:HealthCondition {type: 'Reproductive Health'})
    CREATE (:Disease {type: 'Obesity'})-[:DEFINED_BY]->(:Adiposity {type: 'Adiposity'})
    CREATE (:Disease {type: 'Obesity'})-[:INCREASES_RISK_OF]->(:Disease {type: 'Cardiovascular Disease'})
    CREATE (:Disease {type: 'Obesity'})-[:INCREASES_RISK_OF]->(:Disease {type: 'Neoplasms'})
    CREATE (:Disease {type: 'Obesity'})-[:INCREASES_RISK_OF]->(:Disease {type: 'Type 2 Diabetes Mellitus'})
    CREATE (:Disease {type: 'Obesity'})-[:IS]->(:ChronicDisease {type: 'Chronic Disease'})
    CREATE (:Disease {type: 'Obesity'})-[:IS]->(:DiseaseRiskFactor {type: 'Disease Risk Factor'})
    CREATE (:Disease {type: 'Pneumonia'})-[:CAUSES]->(:Outcome {type: 'Preventable Deaths'})
    CREATE (:Disease {type: 'Salmonellosis'})-[:CAUSED_BY]->(:Bacteria {type: 'Salmonella'})
    CREATE (:Disease {type: 'Salmonellosis'})-[:CHARACTERIZED_BY]->(:Symptom {type: 'Fever'})
    CREATE (:Disease {type: 'Salmonellosis'})-[:CONTRACTED_THROUGH]->(:Food {type: 'Contaminated Food'})
    CREATE (:Disease {type: 'Type 2 Diabetes Mellitus'})-[:IS_A_TYPE_OF]->(:Disease {type: 'Diabetes Mellitus'})
    CREATE (:Disease {type: 'Type1 Diabetes Mellitus'})-[:CHARACTERIZED_BY]->(:Condition {type: 'Insulin Deficiency'})
    CREATE (:Disease {type: 'Type2 Diabetes Mellitus'})-[:CHARACTERIZED_BY]->(:Condition {type: 'Insulin Resistance'})
    CREATE (:Disease {type: 'Variant Creutzfeldt-Jakob Disease (vCJD)'})-[:ASSOCIATED_WITH]->(:Human {type: 'Humans'})
    CREATE (:DiseaseAndHealthTopics {type: 'Disease And Health Topics'})-[:IS_A]->(:Disease {type: 'Dengue Fever'})
    CREATE (:DiseasePrevention {type: 'Disease Prevention'})-[:REQUIRES]->(:FoodSafetyMeasures {type: 'Food Safety Measures'})
    CREATE (:DiseasePrevention {type: 'Hypertension Prevention'})-[:PREVENTED_BY]->(:HealthOutcome {type: 'Balanced Diet'})
    CREATE (:Disorder {type: 'Haemoglobinopathies'})-[:CAN_CAUSE]->(:Condition {type: 'Anaemia'})
    CREATE (:Disorder {type: 'Obesity'})-[:IS_A]->(:Disorder {type: 'Multifactorial Disorder'})
    CREATE (:Disorder {type: 'Overweight and Obesity'})-[:IS]->(:NutritionRelatedDisorder {type: 'Nutrition-Related Disorders'})
    CREATE (:EarlyDetection {type: 'Early Detection'})-[:CAN_CURE]->(:Carcinoma {type: 'Carcinoma'})
    CREATE (:EarlyDetection {type: 'Early Detection'})-[:FOLLOWS]->(:TreatmentPlan {type: 'Treatment Plan'})
    CREATE (:EarlyDetection)-[:FOLLOWS]->(:Therapy)
    CREATE (:EarlyDetectionAndTreatment {type: 'Early Detection and Treatment'})-[:KEY_COMPONENTS_OF_RESPONSE_TO]->(:NonCommunicableDisease {type: 'Non-Communicable Diseases'})
    CREATE (:EasternMediterraneanRegion {type: 'Eastern Mediterranean Region'})-[:IS]->(:RegionalHealthOffice {type: 'Regional Health Office'})
    CREATE (:EasternMediterraneanRegion {type: 'Eastern Mediterranean Region'})-[:IS]->(:WHORegionalOffice {type: 'WHO Regional Office'})
    CREATE (:EasternMediterraneanRegion {type: 'Eastern Mediterranean Region'})-[:IS_PART_OF]->(:RegionalHealthOffice {type: 'Regional Health Office'})
    CREATE (:EasternMediterraneanRegion {type: 'Eastern Mediterranean Region'})-[:PART_OF]->(:WorldHealthOrganization {type: 'World Health Organization'})
    CREATE (:EconomicDevelopment {type: 'Economic Development'})-[:ASSOCIATED_WITH_INCREASED]->(:AddedSugarsConsumption {type: 'Added Sugars Consumption'})
    CREATE (:Education {type: 'Health Education'})-[:SUPPORTS]->(:Strategy {type: 'Sodium Reduction Strategies'})
    CREATE (:Endometriosis {type: 'Endometriosis'})-[:IS]->(:GynecologicalDisorder {type: 'Gynecological Disorder'})
    CREATE (:Endometriosis {type: 'Endometriosis'})-[:IS_A]->(:GynecologicalDisorder {type: 'Gynecological Disorder'})
    CREATE (:EnergyIntake {type: 'Dietary Energy Intake'})-[:IMBALANCE_OF]->(:PhysicalActivity {type: 'Physical Activity Level'})
    CREATE (:Entity {type: 'Donors'})-[:SUPPORTS_RESPONSE_TO]->(:Event {type: 'Health Emergencies'})
    CREATE (:Entity {type: 'Member States'})-[:INCLUDES]->(:Organization {type: 'World Health Organization'})
    CREATE (:Environment {type: 'Obesogenic Environment'})-[:CONTRIBUTES_TO]->(:Disorder {type: 'Obesity'})
    CREATE (:EnvironmentalHealth {type: 'Environmental Health'})-[:IS]->(:PublicHealthConcerns {type: 'Public Health Concerns'})
    CREATE (:EnvironmentalPollution {type: 'Lead Poisoning'})-[:CAUSES]->(:Pollution {type: 'Environmental Pollution'})
    CREATE (:EnzymePreparation {type: 'Enzyme Preparations'})-[:BOOST]->(:BiochemicalReaction {type: 'Biochemical Reactions'})
    CREATE (:EscherichiaColi {type: 'Escherichia coli'})-[:AFFECTS]->(:FoodSafety {type: 'Food Safety'})
    CREATE (:EssentialNutrient {type: 'Sodium'})-[:IS]->(:Micronutrient {type: 'Sodium'})
    CREATE (:EuropeanRegion {type: 'European Region'})-[:IS]->(:RegionalHealthOffice {type: 'Regional Health Office'})
    CREATE (:EuropeanRegion {type: 'European Region'})-[:IS]->(:WHORegionalOffice {type: 'WHO Regional Office'})
    CREATE (:EuropeanRegion {type: 'European Region'})-[:IS_PART_OF]->(:RegionalHealthOffice {type: 'Regional Health Office'})
    CREATE (:EuropeanRegion {type: 'European Region'})-[:PART_OF]->(:WorldHealthOrganization {type: 'World Health Organization'})
    CREATE (:Event {type: 'Nutrition For Growth Summit'})-[:LED_TO_DEVELOPMENT_OF]->(:Strategy {type: 'Global Anaemia Strategy'})
    CREATE (:Event {type: 'Nutrition For Growth Summit'})-[:LED_TO_THE_DEVELOPMENT_OF]->(:Framework {type: 'Anaemia Prevention Framework'})
    CREATE (:Event {type: 'World Diabetes Day'})-[:RAISES_AWARENESS_FOR]->(:Awareness {type: 'Diabetes Awareness'})
    CREATE (:Event {type: 'World Health Assembly'})-[:ADOPTED]->(:Plan {type: 'Maternal And Child Nutrition Plan'})
    CREATE (:Event {type: 'World Health Assembly'})-[:ENDORSED]->(:Policy {type: 'Food Marketing Policy'})
    CREATE (:Exposure {type: 'Lead Exposure'})-[:ACCOUNTS_FOR]->(:Metric {type: 'Disability-Adjusted Life Years (DALYs)'})
    CREATE (:Exposure {type: 'Lead Exposure'})-[:CAUSES]->(:Burden {type: 'Disease Burden'})
    CREATE (:Exposure {type: 'Lead Exposure'})-[:PRIMARILY_DUE_TO]->(:Condition {type: 'Cardiovascular Disease'})
    CREATE (:Exposure {type: 'Low-Level Lead Exposure'})-[:ASSOCIATED_WITH]->(:Condition {type: 'Cognitive Impairment'})
    CREATE (:FAO {type: 'FAO'})-[:CONVENES]->(:JECFA {type: 'JECFA'})
    CREATE (:FeedingMethod {type: 'Exclusive Breastfeeding'})-[:RECOMMENDED_FOR]->(:InfantNutrition {type: 'Infant Nutrition', duration: 'first 6 months'})
    CREATE (:FetalAlcoholSpectrumDisorders {type: 'Fetal Alcohol Spectrum Disorders (FASDs)'})-[:ASSOCIATED_WITH]->(:PrenatalAlcoholExposure {type: 'Prenatal Alcohol Exposure'})
    CREATE (:Field {type: 'Food Safety'})-[:IS_PART_OF]->(:Field {type: 'Public Health'})
    CREATE (:Field {type: 'Nutrition'})-[:INCLUDES]->(:Condition {type: 'Malnutrition'})
    CREATE (:Field {type: 'Nutrition'})-[:INVOLVES]->(:Behavior {type: 'Healthy Eating'})
    CREATE (:Field {type: 'Sanitation'})-[:IS_PART_OF]->(:Field {type: 'Public Health'})
    CREATE (:FinancialInstitution {type: 'World Bank'})-[:PUBLISHED]->(:Framework {type: 'Anaemia Investment Framework'})
    CREATE (:FlavorEnhancer {type: 'Flavor Enhancers'})-[:MODIFY_THE_AROMA_OR_TASTE_OF]->(:FoodProduct {type: 'Food Products'})
    CREATE (:Fluoride {type: 'Fluoride'})-[:USED_IN]->(:ToothDecayPrevention {type: 'Tooth Decay Prevention'})
    CREATE (:FoodGroup {type: 'Fresh Produce'})-[:RICH_IN]->(:Nutrient {type: 'Potassium Consumption'})
    CREATE (:FoodGroup {type: 'Fruit And Vegetable Consumption'})-[:SHOULD_BE_AT_LEAST]->(:DailyDietaryRecommendation {type: 'Daily Dietary Recommendation', amount: '400g'})
    CREATE (:FoodGroup {type: 'Processed And Packaged Foods'})-[:HIGH_IN]->(:Nutrient {type: 'Sodium Intake'})
    CREATE (:Food {type: 'Complementary Foods'})-[:SHOULD_BE_INTRODUCED_FROM]->(:InfantNutrition {type: 'Infant Nutrition', age: '6 months'})
    CREATE (:Food {type: 'Fresh Fruit'})-[:IS_A]->(:SnackingOption {type: 'Healthy Snacking'})
    CREATE (:Food {type: 'Iodized Salt'})-[:RECOMMENDED_FOR]->(:HealthyEatingHabit {type: 'Healthy Eating'})
    CREATE (:Food {type: 'Iron Rich Foods'})-[:HELPS_IN]->(:Prevention {type: 'Anaemia Prevention'})
    CREATE (:Food {type: 'Nutritious Food'})-[:SUPPORTS]->(:Prevention {type: 'Obesity Prevention'})
    CREATE (:Food {type: 'Processed Foods'})-[:HAS]->(:Content {type: 'Sodium Content'})
    CREATE (:Food {type: 'Raw Vegetables'})-[:IS_A]->(:SnackingOption {type: 'Healthy Snacking'})
    CREATE (:Food {type: 'Sugary Snacks'})-[:IS_A]->(:SnackingOption {type: 'Unhealthy Snacking'})
    CREATE (:Food {type: 'Whole Foods'})-[:TYPICALLY_HAS]->(:Content {type: 'Low Sodium Content'})
    CREATE (:FoodAdditive {type: 'Food Additives'})-[:ARE_ADDED_TO]->(:FoodProduct {type: 'Processed Foods'})
    CREATE (:FoodAdditive {type: 'Food Additives'})-[:ARE_ASSESSED_FOR_POTENTIAL_EFFECTS_ON]->(:HumanNutrition {type: 'Human Nutrition'})
    CREATE (:FoodAdditive {type: 'Food Additives'})-[:ARE_USED_FOR]->(:FoodProcessing {type: 'Food Processing'})
    CREATE (:FoodAdditive {type: 'Food Additives'})-[:ASSESSED_FOR_POTENTIAL_HARMFUL_EFFECTS_ON]->(:HumanHealth {type: 'Human Health'})
    CREATE (:FoodAdditive {type: 'Food Additives'})-[:CAN_BE_DERIVED_FROM]->(:AnimalDerivedIngredient {type: 'Animal-Derived Ingredients'})
    CREATE (:FoodAdditive {type: 'Food Additives'})-[:CAN_BE_DERIVED_FROM]->(:MineralBasedIngredient {type: 'Mineral-Based Ingredients'})
    CREATE (:FoodAdditive {type: 'Food Additives'})-[:CAN_BE_DERIVED_FROM]->(:PlantDerivedIngredient {type: 'Plant-Derived Ingredients'})
    CREATE (:FoodAdditive {type: 'Food Additives'})-[:HELP_CONTROL]->(:FoodbornePathogen {type: 'Foodborne Pathogens'})
    CREATE (:FoodAdditive {type: 'Food Additives'})-[:HELP_MAINTAIN]->(:FoodQuality {type: 'Food Quality'})
    CREATE (:FoodAdditive {type: 'Food Additives'})-[:HELP_MAINTAIN]->(:FoodSafety {type: 'Food Safety'})
    CREATE (:FoodAndAgricultureOrganization {type: 'Food and Agriculture Organization'})-[:COLLABORATES_WITH]->(:WorldHealthOrganization {type: 'World Health Organization'})
    CREATE (:FoodColorant {type: 'Food Colorants'})-[:IS_ADDED_TO]->(:FoodProduct {type: 'Food Products'})
    CREATE (:FoodContaminant {type: 'Food Contaminants'})-[:CONTAMINATE]->(:Food {type: 'Food'})
    CREATE (:FoodContaminant {type: 'Food Contaminants'})-[:POSE_RISK_TO]->(:AnimalHealth {type: 'Animal Health'})
    CREATE (:FoodContaminant {type: 'Food Contaminants'})-[:POSE_RISK_TO]->(:HumanHealth {type: 'Human Health'})
    CREATE (:FoodContaminants {type: 'Food Contaminants'})-[:CAUSE]->(:AdverseHealthEffects {type: 'Adverse Health Effects'})
    CREATE (:FoodContaminants {type: 'Food Contaminants'})-[:FOUND_IN]->(:Food {type: 'Food'})
    CREATE (:FoodContaminants {type: 'Food Contaminants'})-[:HARM]->(:Humans {type: 'Humans'})
    CREATE (:FoodContaminants {type: 'Food Contaminants'})-[:HARM]->(:Livestock {type: 'Livestock'})
    CREATE (:FoodIndustry {type: 'Food Industry'})-[:PROMOTES]->(:HealthyEatingOptions {type: 'Healthy Eating Options'})
    CREATE (:FoodIndustry)-[:RESPONSIBLE_FOR_ENSURING]->(:FoodSafety)
    CREATE (:FoodSafety {type: 'Food Safety'})-[:IS_LINKED_TO]->(:FoodSecurity {type: 'Food Security'})
    CREATE (:FoodSafety {type: 'Food Safety'})-[:IS_LINKED_TO]->(:Nutrition {type: 'Nutrition'})
    CREATE (:FoodSafety {type: 'Food Safety'})-[:IS_SHARED_RESPONSIBILITY_AMONG]->(:GovernmentAgencies {type: 'Government Agencies'})
    CREATE (:FoodSafety {type: 'Food Safety'})-[:RELATED_TO]->(:Nutrition {type: 'Nutrition'})
    CREATE (:FoodSafety {type: 'Food Safety'})-[:REQUIRES]->(:OneHealthApproach {type: 'One Health Approach'})
    CREATE (:FoodSafety)-[:CONTRIBUTES_TO]->(:HumanHealth)
    CREATE (:FoodSafety)-[:SUPPORTS]->(:FoodSecurity)
    CREATE (:FoodSecurity {type: 'Food Security'})-[:IMPACTED_BY]->(:ToxicSubstance {type: 'Toxic Substances'})
    CREATE (:FoodSecurity {type: 'Food Security'})-[:IMPACT]->(:Nutrition {type: 'Nutrition'})
    CREATE (:FoodSecurity {type: 'Food Security'})-[:KEEPS_PACE_WITH]->(:GlobalPopulationIncrease {type: 'Global Population Increase'})
    CREATE (:FoodServiceWorkers {type: 'Food Service Workers'})-[:MUST_OBSERVE]->(:FoodSafetyProtocols {type: 'Food Safety Protocols'})
    CREATE (:FoodSupplyChain {type: 'Food Supply Chain'})-[:INCLUDES]->(:AgriculturalProduction {type: 'Agricultural Production'})
    CREATE (:FoodSystems {type: 'Food Systems'})-[:REGULATES]->(:FoodMarketingRegulations {type: 'Food Marketing Regulations'})
    CREATE (:FoodborneIllnesses {type: 'Foodborne Illnesses'})-[:HARMS]->(:EconomicDevelopment {type: 'Economic Development'})
    CREATE (:FoodborneIllnesses {type: 'Foodborne Illnesses'})-[:STRAINS]->(:HealthcareSystems {type: 'Healthcare Systems'})
    CREATE (:FoodborneIllnesses)-[:AFFECTS]->(:EconomicDevelopment)
    CREATE (:FoodborneIllnesses)-[:IMPACTS]->(:PublicHealth)
    CREATE (:FoodbornePathogens {type: 'Foodborne Pathogens'})-[:INCLUDES]->(:BacterialPathogens {type: 'Bacterial Pathogens'})
    CREATE (:FoodbornePathogens {type: 'Foodborne Pathogens'})-[:INCLUDES]->(:ChemicalContaminants {type: 'Chemical Contaminants'})
    CREATE (:FoodbornePathogens {type: 'Foodborne Pathogens'})-[:INCLUDES]->(:ParasiticPathogens {type: 'Parasitic Pathogens'})
    CREATE (:FoodbornePathogens {type: 'Foodborne Pathogens'})-[:INCLUDES]->(:ViralPathogens {type: 'Viral Pathogens'})
    CREATE (:FoodbornePathogens)-[:INCLUDES]->(:Bacteria)
    CREATE (:FoodbornePathogens)-[:INCLUDES]->(:Parasites)
    CREATE (:FoodbornePathogens)-[:INCLUDES]->(:Viruses)
    CREATE (:FoodborneToxins {type: 'Foodborne Toxins'})-[:FOUND_IN]->(:Food {type: 'Food'})
    CREATE (:Foundation {type: 'WHOFoundation'})-[:SUPPORTS]->(:Investment {type: 'InvestmentInGlobalHealth'})
    CREATE (:Framework {type: 'GovernanceFramework'})-[:OVERSEEN_BY]->(:Assembly {type: 'GlobalHealthAssembly'})
    CREATE (:Framework {type: 'GovernanceFramework'})-[:OVERSEEN_BY]->(:Assembly {type: 'WorldHealthAssembly'})
    CREATE (:FreeSugars {type: 'Free Sugars'})-[:CONTRIBUTES_TO_THE_CAUSE_OF]->(:ToothDecay {type: 'Tooth Decay'})
    CREATE (:FreeSugars {type: 'Free Sugars'})-[:INCLUDES]->(:AddedSugars {type: 'Added Sugars'})
    CREATE (:Fruits {type: 'Fruits'})-[:COMPLEMENTARY_TO]->(:Vegetables {type: 'Vegetables'})
    CREATE (:Furanocoumarins {type: 'Furanocoumarins'})-[:ARE]->(:Phytoalexins {type: 'Phytoalexins'})
    CREATE (:Furanocoumarins {type: 'Furanocoumarins'})-[:CAUSE]->(:GastrointestinalToxicity {type: 'Gastrointestinal Toxicity'})
    CREATE (:Furanocoumarins {type: 'Furanocoumarins'})-[:CAUSE]->(:Phototoxicity {type: 'Phototoxicity'})
    CREATE (:Furocoumarins {type: 'Furocoumarins'})-[:ARE]->(:Phytoalexins {type: 'Phytoalexins'})
    CREATE (:Furocoumarins {type: 'Furocoumarins'})-[:CAUSE]->(:Phototoxicity {type: 'Phototoxicity'})
    CREATE (:Furocoumarins {type: 'Furocoumarins'})-[:FOUND_IN]->(:PlantBasedFoods {type: 'Plant-Based Foods'})
    CREATE (:Furocoumarins {type: 'Furocoumarins'})-[:SUBCLASS_OF]->(:Phytochemicals {type: 'Phytochemicals'})
    CREATE (:GeographicArea {type: 'Geographic Regions'})-[:INCLUDES]->(:Region {type: 'African Region'})
    CREATE (:GeographicLocation {type: 'Geographic Locations'})-[:DIVIDED_INTO]->(:GeographicRegion {type: 'Geographic Regions'})
    CREATE (:GeographicLocation {type: 'Geographic Locations'})-[:HAS]->(:HealthData {type: 'Health Data'})
    CREATE (:GeographicLocation {type: 'Geographic Locations'})-[:PART_OF]->(:GeographicRegion {type: 'Geographic Regions'})
    CREATE (:GeographicLocation {type: 'Geographic Locations'})-[:PROVIDES]->(:HealthData {type: 'Health Data'})
    CREATE (:GeographicRegion {type: 'Geographic Regions'})-[:INCLUDES]->(:AfricaRegion {type: 'Africa Region'})
    CREATE (:GeographicRegion {type: 'Geographic Regions'})-[:INCLUDES]->(:AmericasRegion {type: 'Americas Region'})
    CREATE (:GeographicRegion {type: 'Geographic Regions'})-[:INCLUDES]->(:EuropeanRegion {type: 'European Region'})
    CREATE (:GeographicRegion {type: 'Geographic Regions'})-[:INCLUDES]->(:GeographicSubRegion {type: 'Africa Region'})
    CREATE (:GeographicRegion {type: 'Geographic Regions'})-[:SUBJECT_TO]->(:PolicyFramework {type: 'Health Policy Frameworks'})
    CREATE (:GlobalActionPlan {type: 'Global Alcohol Action Plan'})-[:INCLUDED_IN]->(:DevelopmentGoals {type: 'Sustainable Development Goals'})
    CREATE (:GlobalActionPlanForNCDs)-[:TARGETS]->(:NonCommunicableDiseases)
    CREATE (:GlobalBurdenOfDiseaseStudy {type: 'Global Burden of Disease Study'})-[:REPORTS]->(:OsteoarthritisPrevalence {type: 'Osteoarthritis Prevalence'})
    CREATE (:GlobalBurdenOfFoodborneDiseasesReport)-[:ESTIMATES]->(:GlobalBurdenOfFoodborneDiseases)
    CREATE (:GlobalGovernance {type: 'Global Governance'})-[:REQUIRES_EFFECTIVE]->(:Substance {type: 'Alcohol Consumption'})
    CREATE (:GlobalGovernance {type: 'Global Health Governance'})-[:REGULATES]->(:Policy {type: 'Nutrition Policy'})
    CREATE (:GlobalHealthBurden {type: 'Global Health Burden'})-[:CONTRIBUTES_TO]->(:Poisoning {type: 'Lead Poisoning'})
    CREATE (:GlobalHealthInitiative {type: 'Global Health Initiative'})-[:PROMOTES]->(:PhysicalActivity {type: 'Physical Activity'})
    CREATE (:GlobalHealthOrganization {type: 'Global Health Organization'})-[:IS]->(:GlobalHealth {type: 'Global Health'})
    CREATE (:GlobalHealthOrganization {type: 'Global Health Organization'})-[:IS]->(:InternationalHealthAgency {type: 'International Health Agency'})
    CREATE (:GlobalHealthRegion {type: 'Global Health Regions'})-[:ARE_PART_OF]->(:GeographicRegion {type: 'Geographic Regions'})
    CREATE (:GlobalInformationSystem {type: 'Global Information System on Alcohol and Health'})-[:PRESENTS_DATA_ON]->(:Substance {type: 'Alcohol Consumption'})
    CREATE (:GlobalInitiativeOnCancerRegistries)-[:MONITORS]->(:CancerIncidence)
    CREATE (:GlobalMonitoringFramework {type: 'Global Monitoring Framework for Noncommunicable Diseases'})-[:MONITORS]->(:Disease {type: 'Noncommunicable Diseases'})
    CREATE (:GlobalNCDActionPlan)-[:INCLUDES]->(:DietaryTargets)
    CREATE (:GlobalNCDActionPlan)-[:TARGETS]->(:NonCommunicableDiseases)
    CREATE (:GlobalPopulationIncrease {type: 'Global Population Increase'})-[:OCCURS_IN]->(:LowIncomeCountries {type: 'Low-Income Countries'})
    CREATE (:GlobalStrategyForWomensChildrensAndAdolescentsHealth)-[:ADDRESSES]->(:Malnutrition)
    CREATE (:GlobalStrategyForWomensChildrensAndAdolescentsHealth)-[:FOCUSES_ON]->(:AdolescentNutrition)
    CREATE (:GlobalStrategyForWomensChildrensAndAdolescentsHealth)-[:FOCUSES_ON]->(:ChildNutrition)
    CREATE (:GlobalStrategyForWomensChildrensAndAdolescentsHealth)-[:FOCUSES_ON]->(:MaternalHealth)
    CREATE (:Glycoalkaloids {type: 'Glycoalkaloids'})-[:ARE]->(:SolanaceaeAlkaloids {type: 'Solanaceae Alkaloids'})
    CREATE (:Glycoalkaloids {type: 'Glycoalkaloids'})-[:FOUND_IN]->(:Nightshades {type: 'Nightshades'})
    CREATE (:Glycoalkaloids {type: 'Glycoalkaloids'})-[:FOUND_IN]->(:Solanaceae {type: 'Solanaceae'})
    CREATE (:Goal {type: 'Global Nutrition Goals'})-[:AIMS]->(:Outcome {type: 'Growth Promotion'})
    CREATE (:Government {type: 'National Governments'})-[:DEVELOPS]->(:Guidelines {type: 'Physical Activity Guidelines'})
    CREATE (:GovernmentPolicy)-[:REDUCES]->(:ModifiableRiskFactor)
    CREATE (:Guideline {type: 'Child Growth Standards'})-[:GUIDES]->(:Field {type: 'Pediatric Development'})
    CREATE (:Guideline {type: 'Dietary Guidelines'})-[:INCLUDES]->(:Activity {type: 'Physical Activity'})
    CREATE (:Guideline {type: 'Safe Food Handling Guidelines'})-[:PROMOTES]->(:Awareness {type: 'Food Safety Awareness'})
    CREATE (:Guideline {type: 'WHO Guidelines'})-[:PROVIDES]->(:Management {type: 'Lead Exposure Management'})
    CREATE (:Guidelines {type: 'Dietary Guidelines'})-[:PROVIDES]->(:Recommendations {type: 'Sodium Intake Recommendations'})
    CREATE (:HIV_AIDS {type: 'HIV/AIDS'})-[:CAUSES]->(:Haemolysis {type: 'Haemolysis'})
    CREATE (:Habit {type: 'Healthy Eating'})-[:PREVENTS]->(:Disease {type: 'Cardiovascular Disease'})
    CREATE (:Habit {type: 'Healthy Eating'})-[:ESSENTIAL_FOR]->(:Field {type: 'Nutrition'})
    CREATE (:Haemoglobinopathy {type: 'Haemoglobinopathies'})-[:INCLUDES]->(:Thalassemia {type: 'Thalassemia'})
    CREATE (:HazardousDrinking {type: 'Hazardous Drinking'})-[:LEADS_TO]->(:SocialConsequences {type: 'Social Consequences'})
    CREATE (:Health {type: 'Maternal Health'})-[:AFFECTS]->(:Exposure {type: 'Lead Exposure'})
    CREATE (:HealthBenefit {type: 'Reduced Sodium Consumption'})-[:CAN_PREVENT]->(:Disease {type: 'Cardiovascular Disease'})
    CREATE (:HealthCondition {type: 'Malnutrition'})-[:RELATED_TO]->(:HealthCondition {type: 'Obesity'})
    CREATE (:HealthCondition {type: 'Obesity'})-[:TRACKED_BY]->(:DataRepository {type: 'Global Health Observatory (GHO)'})
    CREATE (:HealthConditions {type: 'Health Conditions'})-[:IS]->(:GlobalHealthOrganization {type: 'Global Health Organization'})
    CREATE (:HealthIndicator {type: 'Female Anaemia Prevalence'})-[:IS_TARGET_FOR]->(:SustainableDevelopmentGoal {type: 'Sustainable Development Goals'})
    CREATE (:HealthInitiative {type: 'Dietary Fat Reduction'})-[:OPEN_FOR]->(:GeographicScope {type: 'Country-Level Initiatives'})
    CREATE (:HealthInterventions {type: 'Health Interventions'})-[:OFTEN_CHARACTERIZED_BY]->(:DiseaseSpecificApproach {type: 'Disease-Specific Approach'})
    CREATE (:HealthIssue {type: 'Adolescent Health'})-[:IS_ADDRESSED_BY]->(:Initiative {type: 'Global Accelerated Action For The Health Of Adolescents'})
    CREATE (:HealthProgram {type: 'Maternal, Infant, and Young Child Nutrition'})-[:ADDRESSES]->(:MedicalCondition {type: 'Iron Deficiency Anemia'})
    CREATE (:HealthRecommendation {type: 'Nutrition Guidelines'})-[:GUIDES]->(:HealthOutcome {type: 'Sodium Intake Reduction'})
    CREATE (:HealthRisk {type: 'Obesity Prevention'})-[:CAUSED_BY]->(:UnhealthyHabit {type: 'Unhealthy Eating Habits'})
    CREATE (:HealthTopics {type: 'Health Topics'})-[:IS]->(:DiseaseCategories {type: 'Disease Categories'})
    CREATE (:HealthTopics {type: 'Health Topics'})-[:IS_COVERED_BY]->(:GlobalHealthOrganization {type: 'Global Health Organization'})
    CREATE (:HealthTrend {type: 'Childhood Obesity'})-[:INCREASED_BY_TENFOLD_IN]->(:TimePeriod {type: 'Four Decades of Global Health Trends'})
    CREATE (:HealthcareExpenditure)-[:DRAINS]->(:HouseholdIncome)
    CREATE (:HealthcareProviders {type: 'Healthcare Providers'})-[:PROVIDES]->(:NutritionCounseling {type: 'Nutrition Counseling'})
    CREATE (:HealthcareSector {type: 'Healthcare Sector'})-[:IDENTIFIES]->(:DiseaseRiskManagement {type: 'Disease Risk Management'})
    CREATE (:HealthyEatingHabits {type: 'Healthy Eating Habits'})-[:CORRELATES_WITH]->(:RegularPhysicalActivity {type: 'Regular Physical Activity'})
    CREATE (:HealthyHabit {type: 'Healthy Eating'})-[:SHOULD_BE_PROMOTED_IN]->(:Setting {type: 'Food Environments'})
    CREATE (:HeatRelatedIllness {type: 'Heat-Related Illness'})-[:IS]->(:EnvironmentalHealthHazard {type: 'Environmental Health Hazard'})
    CREATE (:HeatRelatedIllness {type: 'Heat-Related Illness'})-[:IS_A]->(:EnvironmentalHealthHazard {type: 'Environmental Health Hazard'})
    CREATE (:Hepatitis {type: 'Hepatitis'})-[:CAUSES]->(:Carcinoma {type: 'Carcinoma'})
    CREATE (:HerbsAndSpices {type: 'Culinary Herbs And Spices'})-[:USED_FOR]->(:Enhancement {type: 'Flavour Enhancement'})
    CREATE (:HerpesSimplex {type: 'Herpes Simplex'})-[:IS]->(:InfectiousDisease {type: 'Infectious Disease'})
    CREATE (:HerpesSimplex {type: 'Herpes Simplex'})-[:IS_A]->(:InfectiousDisease {type: 'Infectious Disease'})
    CREATE (:Hormone {type: 'Insulin'})-[:REGULATES]->(:Substance {type: 'Blood Glucose'})
    CREATE (:HumanPapillomavirus {type: 'Human Papillomavirus (HPV)'})-[:CAUSES]->(:Carcinoma {type: 'Carcinoma'})
    CREATE (:Indicator {type: 'Body Mass Index (BMI)'})-[:IS]->(:AnthropometricIndicator {type: 'Anthropometric Indicator'})
    CREATE (:Industry {type: 'Food Marketing'})-[:TARGETS]->(:Population {type: 'Pediatric Population'})
    CREATE (:Infection {type: 'Gastrointestinal Infection'})-[:CAUSED_BY]->(:Pathogen {type: 'Foodborne And Waterborne Pathogens'})
    CREATE (:InfectiousDisease {type: 'Infectious diseases'})-[:INCLUDES]->(:Malaria {type: 'Malaria'})
    CREATE (:InfectiousDisease {type: 'Infectious diseases'})-[:INCLUDES]->(:Schistosomiasis {type: 'Schistosomiasis'})
    CREATE (:Inflammation {type: 'Inflammation'})-[:CAUSES]->(:AnaemiaOfChronicDisease {type: 'Anaemia of chronic disease'})
    CREATE (:Information {type: 'Organizational Information'})-[:IS_PART_OF]->(:Opportunity {type: 'Career Opportunities'})
    CREATE (:Ingredient {type: 'Partially Hydrogenated Oils'})-[:FOUND_IN]->(:FoodCategory {type: 'Processed Foods'})
    CREATE (:Initiative {type: 'Childhood Obesity Prevention'})-[:AIMS_TO_END]->(:Disease {type: 'Pediatric Obesity'})
    CREATE (:Initiative {type: 'Global Alliance to Eliminate Lead Paint'})-[:AIMS_TO_ENCOURAGE]->(:Regulation {type: 'Lead Paint Regulations'})
    CREATE (:Initiative {type: 'Global Diabetes Compact'})-[:AIMS_TO_IMPROVE]->(:Care {type: 'Diabetes Prevention and Care'})
    CREATE (:Initiative {type: 'REPLACETrans Fat Initiative'})-[:IS]->(:Package {type: 'Public Health Action Package'})
    CREATE (:IntegratedCareForOlderPeople {type: 'Integrated Care for Older People'})-[:INVOLVES]->(:PersonCentredAssessment {type: 'Person-Centred Assessment'})
    CREATE (:InternationalAgencyForResearchOnCancer)-[:CONDUCTS]->(:CancerResearch)
    CREATE (:InternationalCodeOfConductOnPesticideManagement {type: 'International Code of Conduct on Pesticide Management'})-[:GUIDES]->(:IntegratedPestManagement {type: 'Integrated Pest Management (IPM)'})
    CREATE (:Intervention {type: 'Dietary Interventions'})-[:SUPPORTS]->(:Prevention {type: 'Obesity Prevention'})
    CREATE (:JECFA {type: 'JECFA'})-[:AFFILIATED_WITH]->(:FAO {type: 'FAO'})
    CREATE (:JECFA {type: 'JECFA'})-[:AFFILIATED_WITH]->(:WHO {type: 'WHO'})
    CREATE (:JECFA {type: 'JECFA'})-[:EVALUATES]->(:FoodContaminants {type: 'Food Contaminants'})
    CREATE (:JECFA {type: 'JECFA'})-[:EVALUATES_THE_SAFETY_OF]->(:FoodAdditive {type: 'Food Additives'})
    CREATE (:JECFASafetyEvaluation {type: 'JECFA Safety Evaluation'})-[:REQUIRED_FOR_INTERNATIONAL_USE]->(:FoodAdditive {type: 'Food Additives'})
    CREATE (:JointFAOWHOExpertCommitteeOnFoodAdditives {type: 'Joint FAO/WHO Expert Committee on Food Additives'})-[:EVALUATES_THE_SAFETY_OF]->(:FoodAdditive {type: 'Food Additives'})
    CREATE (:JointFAOWHOExpertCommitteeOnFoodAdditives {type: 'Joint FAO/WHO Expert Committee on Food Additives'})-[:SETS]->(:TolerableDailyIntake {type: 'Tolerable Daily Intake'})
    CREATE (:JointFAOWHOMeetingOnPesticideResidues {type: 'Joint FAO/WHO Meeting on Pesticide Residues (JMPR)'})-[:CONDUCTS_RISK_ASSESSMENTS]->(:PesticideResiduesInFood {type: 'Pesticide Residues in Food'})
    CREATE (:JointReplacementSurgery {type: 'Joint Replacement Surgery'})-[:RESULTS_IN]->(:PainReduction {type: 'Pain Reduction'})
    CREATE (:Label {type: 'Nutrition Labels'})-[:SHOULD_BE_CHECKED_FOR]->(:Nutrient {type: 'Sodium Content'})
    CREATE (:Labelling {type: 'Nutrition Labelling'})-[:DISPLAYS]->(:Content {type: 'Sodium Content'})
    CREATE (:Lectins {type: 'Lectins'})-[:ARE]->(:Antinutrients {type: 'Antinutrients'})
    CREATE (:Lectins {type: 'Lectins'})-[:FOUND_IN]->(:Legumes {type: 'Legumes'})
    CREATE (:Lifestyle {type: 'Healthy Lifestyle'})-[:CONTRIBUTES_TO]->(:Prevention {type: 'Type 2 Diabetes Prevention'})
    CREATE (:Listeriosis {type: 'Listeriosis'})-[:AFFECTS]->(:FoodSafety {type: 'Food Safety'})
    CREATE (:LowAndMiddleIncomeCountries {type: 'Low- and Middle-Income Countries'})-[:DISPROPORTIONATELY_AFFECTS]->(:NonCommunicableDisease {type: 'Non-Communicable Diseases'})
    CREATE (:LowCalorieSweetener {type: 'Low-Calorie Sweeteners'})-[:ARE_USED_AS_AN_ALTERNATIVE_TO]->(:Sucrose {type: 'Sucrose'})
    CREATE (:Malnutrition {type: 'Malnutrition'})-[:CAUSED_BY]->(:EnergyImbalance {type: 'Energy Imbalance'})
    CREATE (:Malnutrition {type: 'Malnutrition'})-[:FORM_OF]->(:Obesity {type: 'Obesity'})
    CREATE (:Malnutrition {type: 'Malnutrition'})-[:FORM_OF]->(:Overweight {type: 'Overweight'})
    CREATE (:Malnutrition {type: 'Malnutrition'})-[:FORM_OF]->(:Undernutrition {type: 'Undernutrition'})
    CREATE (:Malnutrition {type: 'Malnutrition'})-[:INCLUDES]->(:MicronutrientDeficiency {type: 'Micronutrient Deficiency'})
    CREATE (:Malnutrition {type: 'Malnutrition'})-[:INCLUDES]->(:Obesity {type: 'Obesity'})
$$) AS (a agtype);
