SELECT * FROM create_graph('who_factsheets_part3of4');
SELECT * FROM cypher('who_factsheets_part3of4', $$
    CREATE (:Malnutrition {type: 'Malnutrition'})-[:INCLUDES]->(:Overweight {type: 'Overweight'})
    CREATE (:Malnutrition {type: 'Malnutrition'})-[:INCLUDES]->(:OverweightAndObesity {type: 'Overweight and Obesity'})
    CREATE (:Malnutrition {type: 'Malnutrition'})-[:INCLUDES]->(:OverweightStatus {type: 'Overweight Status'})
    CREATE (:Malnutrition {type: 'Malnutrition'})-[:INCLUDES]->(:Undernutrition {type: 'Undernutrition'})
    CREATE (:Malnutrition {type: 'Malnutrition'})-[:INCLUDES]->(:UnderweightStatus {type: 'Underweight Status'})
    CREATE (:Malnutrition {type: 'Malnutrition'})-[:INFLUENCED_BY]->(:SocioeconomicFactors {type: 'Socioeconomic Factors'})
    CREATE (:MarineBiotoxins {type: 'Marine Biotoxins'})-[:FOUND_IN]->(:Shellfish {type: 'Shellfish'})
    CREATE (:MaternalHealth)-[:PART_OF]->(:GlobalStrategyForWomensChildrensAndAdolescentsHealth)
    CREATE (:MaternalNutrition {type: 'Maternal Nutrition'})-[:REQUIRES]->(:GestationalWeightGain {type: 'Gestational Weight Gain'})
    CREATE (:Mechanism {type: 'Accountability Mechanisms'})-[:ENSURED_THROUGH]->(:Process {type: 'External Auditing Processes'})
    CREATE (:MediaAndCommunications {type: 'Media and Communications'})-[:INCLUDES]->(:NewsHeadline {type: 'News Headlines'})
    CREATE (:MediaAndCommunications {type: 'Media and Communications'})-[:INCLUDES]->(:PressRelease {type: 'Press Releases'})
    CREATE (:MediaCenter {type: 'Media Center'})-[:FEATURES]->(:TopStory {type: 'Top Stories'})
    CREATE (:MediaCenter {type: 'Media Center'})-[:PUBLISHES]->(:Publication {type: 'Publications'})
    CREATE (:MediaCentre {type: 'Media Centre'})-[:CONTAINS]->(:NewsArticle {type: 'News Articles'})
    CREATE (:MediaCentre {type: 'Media Centre'})-[:DISPLAYS]->(:NewsHighlight {type: 'News Highlights'})
    CREATE (:MedicalConcept {type: 'Early Detection Of Colorectal Cancer'})-[:IMPROVES]->(:MedicalProcedure {type: 'Colorectal Cancer Treatment'})
    CREATE (:MedicalConcept {type: 'Genetic Risk Assessment'})-[:AIDS_IN]->(:MedicalConcept {type: 'Colorectal Cancer Risk Assessment'})
    CREATE (:MedicalCondition {type: 'Iron Deficiency Anemia'})-[:RELATED_TO]->(:MedicalCondition {type: 'Malnutrition'})
    CREATE (:MedicalMeasurement {type: 'Hemoglobin Concentrations'})-[:USED_FOR]->(:MedicalDiagnosis {type: 'Diagnosis of Anemia'})
    CREATE (:MedicalProcedure {type: 'Adjuvant Chemotherapy'})-[:MAY_BE_FOLLOWED_BY]->(:MedicalProcedure {type: 'Targeted Therapy'})
    CREATE (:MedicalProcedure {type: 'Chemotherapy'})-[:IS_A_FORM_OF]->(:MedicalProcedure {type: 'Colorectal Cancer Treatment'})
    CREATE (:MedicalProcedure {type: 'Colonoscopy'})-[:IS_A]->(:MedicalProcedure {type: 'Diagnostic Colonoscopy'})
    CREATE (:MedicalProcedure {type: 'Colorectal Cancer Screening'})-[:LEADS_TO]->(:MedicalConcept {type: 'Early Detection Of Colorectal Cancer'})
    CREATE (:MedicalProcedure {type: 'Surgical Intervention'})-[:MAY_BE_COMBINED_WITH]->(:MedicalProcedure {type: 'Adjuvant Chemotherapy'})
    CREATE (:MedicalProcedure {type: 'Surgical Resection'})-[:IS_A_FORM_OF]->(:MedicalProcedure {type: 'Colorectal Cancer Treatment'})
    CREATE (:MedicalService {type: 'Genetic Counselling And Testing'})-[:INCLUDES]->(:MedicalConcept {type: 'Genetic Risk Assessment'})
    CREATE (:MedicalService {type: 'Genetic Counselling'})-[:INVOLVES]->(:MedicalProcedure {type: 'Genetic Risk Assessment'})
    CREATE (:MedicalService {type: 'Palliative Care'})-[:AIMS_TO_PROVIDE]->(:MedicalConcept {type: 'Symptom Management'})
    CREATE (:MedicalSpecialty {type: 'Pediatric Oncology'})-[:TREATED_WITH]->(:TherapeuticAgent {type: 'Antineoplastic Agents'})
    CREATE (:MedicalTest {type: 'Fecal Immunochemical Tests'})-[:DETECTS]->(:Disease {type: 'Colorectal Cancer'})
    CREATE (:MedicalTest {type: 'Fecal Occult Blood Test'})-[:IS_A_TYPE_OF]->(:MedicalTest {type: 'Stool Based Screening Tests'})
    CREATE (:MedicalTest {type: 'Fecal Occult Blood Test'})-[:MAY_LEAD_TO]->(:MedicalProcedure {type: 'Colonoscopy'})
    CREATE (:MedicalTest {type: 'Fecal Occult BloodTest'})-[:IS_A_TYPE_OF]->(:MedicalTest {type: 'Fecal Immunochemical Tests'})
    CREATE (:MedicalTest {type: 'Stool Based Screening Tests'})-[:DETECTS]->(:Disease {type: 'Colorectal Cancer'})
    CREATE (:Medication {type: 'Metformin'})-[:IS_A_MEDICATION_FOR]->(:Disease {type: 'Type 2 Diabetes Management'})
    CREATE (:MentalHealthDisorder {type: 'Mental Health Disorder'})-[:IS_A]->(:MentalHealthCondition {type: 'Mental Health Condition'})
    CREATE (:MentalHealthDisorders {type: 'Mental Health Disorders'})-[:IS]->(:ChronicConditions {type: 'Chronic Conditions'})
    CREATE (:MentalHealthDisorders {type: 'Mental Health Disorders'})-[:IS]->(:MentalHealthCondition {type: 'Mental Health Condition'})
    CREATE (:Methodology {type: 'Risk Assessment Methodologies'})-[:COMPLIANT_WITH]->(:Standard {type: 'International Food Standards'})
    CREATE (:Metric {type: 'Body Mass Index (BMI)'})-[:MEASURES]->(:NutritionStatus {type: 'Adult Nutrition Status'})
    CREATE (:MicrobialToxins {type: 'Microbial Toxins'})-[:IS_A]->(:FoodContaminants {type: 'Food Contaminants'})
    CREATE (:MicrobialToxins {type: 'Microbial Toxins'})-[:PRODUCE]->(:FoodborneToxins {type: 'Foodborne Toxins'})
    CREATE (:Micronutrient {type: 'Sodium'})-[:IS]->(:EssentialNutrient {type: 'Sodium'})
    CREATE (:MicronutrientDeficiency {type: 'Micronutrient Deficiency'})-[:INCLUDES]->(:IodineDeficiency {type: 'Iodine Deficiency'})
    CREATE (:MicronutrientDeficiency {type: 'Micronutrient Deficiency'})-[:INCLUDES]->(:IronDeficiency {type: 'Iron Deficiency'})
    CREATE (:MicronutrientDeficiency {type: 'Micronutrient Deficiency'})-[:INCLUDES]->(:VitaminADeficiency {type: 'Vitamin A Deficiency'})
    CREATE (:MicronutrientDeficiency {type: 'Micronutrient Deficiency'})-[:INCLUDES]->(:VitaminDeficiency {type: 'Vitamin Deficiency'})
    CREATE (:Mineral {type: 'Iron'})-[:ESSENTIAL_FOR_PRODUCTION_OF]->(:Protein {type: 'Haemoglobin'})
    CREATE (:Mineral {type: 'Minerals'})-[:FOUND_IN]->(:Food {type: 'Fresh Fruit'})
    CREATE (:Monkeypox {type: 'Monkeypox'})-[:IS_A]->(:InfectiousDisease {type: 'Infectious Disease'})
    CREATE (:MortalityRate {type: 'Mortality Rate'})-[:EQUALS]->(:AnnualDeaths {type: '3 Million'})
    CREATE (:MortalityRate {type: 'Mortality Rate'})-[:MAJORITY_AMONG]->(:Demographic {type: 'Males'})
    CREATE (:MotorVehicleCrashes {type: 'Motor Vehicle Crashes'})-[:CONTRIBUTES_TO]->(:AlcoholAttributableMortality {type: 'Alcohol-Attributable Mortality'})
    CREATE (:Mpox {type: 'Mpox'})-[:IS]->(:InfectiousDisease {type: 'Infectious Disease'})
    CREATE (:MuscimolAndMuscarine {type: 'Muscimol and Muscarine'})-[:ARE]->(:MushroomToxins {type: 'Mushroom Toxins'})
    CREATE (:MuscimolAndMuscarine {type: 'Muscimol and Muscarine'})-[:FOUND_IN]->(:WildMushrooms {type: 'Wild Mushrooms'})
    CREATE (:Mycotoxins {type: 'Mycotoxins'})-[:AFFECTS]->(:FoodSafety {type: 'Food Safety'})
    CREATE (:Mycotoxins {type: 'Mycotoxins'})-[:ARE]->(:FungalToxins {type: 'Fungal Toxins'})
    CREATE (:Mycotoxins {type: 'Mycotoxins'})-[:ARE]->(:FungalToxins {type: 'FungalToxins'})
    CREATE (:Mycotoxins {type: 'Mycotoxins'})-[:IS_A]->(:FoodContaminants {type: 'Food Contaminants'})
    CREATE (:Mycotoxins {type: 'Mycotoxins'})-[:PRODUCE]->(:FoodborneToxins {type: 'Foodborne Toxins'})
    CREATE (:Mycotoxins {type: 'Mycotoxins'})-[:SURVIVE]->(:FoodProcessing {type: 'Food Processing'})
    CREATE (:Mycotoxins {type: 'Mycotoxins'})-[:SURVIVE]->(:FoodProcessing {type: 'FoodProcessing'})
    CREATE (:NationalRegulatoryAgencies {type: 'National Regulatory Agencies'})-[:MONITOR]->(:FoodSupply {type: 'Food Supply'})
    CREATE (:NationalSurveillanceSystems {type: 'National Surveillance Systems'})-[:MONITOR]->(:FoodborneIllnesses {type: 'Foodborne Illnesses'})
    CREATE (:NaturalToxins {type: 'Natural Toxins'})-[:AFFECTS]->(:FoodSafety {type: 'Food Safety'})
    CREATE (:Nematode {type: 'Nematodes'})-[:ENTER_FOOD_CHAIN_VIA]->(:Water {type: 'Water'})
    CREATE (:Neoplasm {type: 'Colorectal Cancer'})-[:IS_A_TYPE_OF]->(:Disease {type: 'Neoplasm'})
    CREATE (:Neoplasm {type: 'Colorectal Cancer'})-[:IS_A_TYPE_OF]->(:Neoplasm {type: 'Neoplasm'})
    CREATE (:NeoplasticCells {type: 'Neoplastic Cells'})-[:CAN_LEAD_TO]->(:Metastasis {type: 'Metastasis'})
    CREATE (:Network {type: 'International Food Safety Network'})-[:MANAGES]->(:Risk {type: 'Food Safety Risks'})
    CREATE (:Neurodevelopment {type: 'Neurodevelopment'})-[:AFFECTS]->(:ToxicSubstance {type: 'Lead'})
    CREATE (:NewsAndMedia {type: 'News and Media'})-[:INCLUDES]->(:PressRelease {type: 'Press Releases'})
    CREATE (:NonCommunicableDisease {type: 'Non-Communicable Diseases'})-[:ALSO_KNOWN_AS]->(:ChronicDisease {type: 'Chronic Diseases'})
    CREATE (:NonCommunicableDisease {type: 'Non-Communicable Diseases'})-[:INCLUDES]->(:Cancer {type: 'Cancer'})
    CREATE (:NonCommunicableDisease {type: 'Non-Communicable Diseases'})-[:INCLUDES]->(:CardiovascularDisease {type: 'Cardiovascular Disease'})
    CREATE (:NonCommunicableDisease {type: 'Non-Communicable Diseases'})-[:INCLUDES]->(:ChronicObstructivePulmonaryDisease {type: 'Chronic Obstructive Pulmonary Disease'})
    CREATE (:NonCommunicableDisease {type: 'Non-Communicable Diseases'})-[:INCLUDES]->(:DiabetesMellitus {type: 'Diabetes Mellitus'})
    CREATE (:NonCommunicableDisease)-[:ASSOCIATED_WITH]->(:ModifiableRiskFactor)
    CREATE (:NonCommunicableDisease)-[:IMPEDS]->(:PovertyAlleviation)
    CREATE (:NonCommunicableDisease)-[:INCREASES]->(:HealthcareExpenditure)
    CREATE (:NonCommunicableDiseaseManagement)-[:INCLUDES]->(:EarlyDetectionAndTreatment)
    CREATE (:NonCommunicableDiseases)-[:RELATED_TO]->(:GlobalStrategyForWomensChildrensAndAdolescentsHealth)
    CREATE (:NonTyphoidalSalmonellosis {type: 'Non-typhoidal Salmonellosis'})-[:AFFECTS]->(:FoodSafety {type: 'Food Safety'})
    CREATE (:NoncommunicableDisease {type: 'Noncommunicable Diseases (NCDs)'})-[:INCLUDES]->(:Cancer {type: 'Cancer'})
    CREATE (:NoncommunicableDisease {type: 'Noncommunicable Diseases (NCDs)'})-[:INCLUDES]->(:CardiovascularDisease {type: 'Cardiovascular Disease (CVD)'})
    CREATE (:NoncommunicableDisease {type: 'Noncommunicable Diseases (NCDs)'})-[:INCLUDES]->(:DiabetesMellitus {type: 'Diabetes Mellitus'})
    CREATE (:Nutrient {type: 'Added Sugars'})-[:CONTRIBUTES_TO]->(:HealthCondition {type: 'Tooth Decay'})
    CREATE (:Nutrient {type: 'Added Sugars'})-[:CONTRIBUTES_TO]->(:HealthCondition {type: 'Weight Gain'})
    CREATE (:Nutrient {type: 'Added Sugars'})-[:INCREASES_RISK_OF]->(:HealthCondition {type: 'Cardiovascular Disease'})
    CREATE (:Nutrient {type: 'Dietary Trans Fat'})-[:ORIGINATES_FROM]->(:Ingredient {type: 'Partially Hydrogenated Oils'})
    CREATE (:Nutrient {type: 'Dietary Trans Fat'})-[:RISK_FACTOR_FOR]->(:Disease {type: 'Cardiovascular Disease'})
    CREATE (:Nutrient {type: 'Monounsaturated Fatty Acids'})-[:FOUND_IN]->(:FoodCategory {type: 'Nuts Seeds Avocados And Olive Oil'})
    CREATE (:Nutrient {type: 'Polyunsaturated Fatty Acids'})-[:FOUND_IN]->(:FoodCategory {type: 'Vegetable Oils And Fatty Fish'})
    CREATE (:Nutrient {type: 'Potassium Consumption'})-[:CAN_MITIGATE_THE_NEGATIVE_EFFECTS_OF]->(:Nutrient {type: 'Sodium Consumption'})
    CREATE (:Nutrient {type: 'Sodium Intake'})-[:SHOULD_BE_LESS_THAN]->(:DailyDietaryRecommendation {type: 'Daily Dietary Recommendation', amount: '5g'})
    CREATE (:NutrientIntake {type: 'Sodium Consumption'})-[:IMPACTS]->(:Disease {type: 'Cardiovascular Disease'})
    CREATE (:Nutrition {type: 'Nutrition'})-[:HELPS_PREVENT]->(:ChronicDiseases {type: 'Chronic Diseases'})
    CREATE (:Nutrition {type: 'Nutrition'})-[:PREVENTS]->(:Malnutrition {type: 'Malnutrition'})
    CREATE (:NutritionGovernance {type: 'Nutrition Governance'})-[:INCLUDES]->(:AccountabilityMechanism {type: 'Accountability Mechanisms'})
    CREATE (:NutritionLabelling {type: 'Nutrition Labelling'})-[:REQUIRES_INDICATION_OF]->(:FoodAdditive {type: 'Food Additives'})
    CREATE (:NutritionalDeficiency {type: 'Nutritional Deficiency'})-[:INCREASED_BY]->(:Exposure {type: 'Lead Exposure'})
    CREATE (:NutritionalIntervention {type: 'Nutritional interventions'})-[:INCLUDES]->(:IronSupplementation {type: 'Iron supplementation'})
    CREATE (:Obesity {type: 'Obesity'})-[:INCREASES_RISK_OF]->(:Carcinoma {type: 'Carcinoma'})
    CREATE (:Obesity {type: 'Obesity'})-[:INCREASES_RISK_OF]->(:NonCommunicableDiseases {type: 'Non-Communicable Diseases'})
    CREATE (:Obesity {type: 'Obesity'})-[:LINKED_TO]->(:NonCommunicableDiseases {type: 'Non-Communicable Diseases'})
    CREATE (:ObesityPrevention {type: 'Obesity Prevention'})-[:REQUIRES]->(:MultisectoralApproaches {type: 'Multisectoral Approaches'})
    CREATE (:OccupationalHazard {type: 'Occupational Hazard'})-[:CAUSED_BY]->(:Poisoning {type: 'Lead Poisoning'})
    CREATE (:Office {type: 'Regional Offices'})-[:INCLUDES]->(:Region {type: 'WHO African Region'})
    CREATE (:Office {type: 'Regional Offices'})-[:INCLUDES]->(:Region {type: 'WHO Eastern Mediterranean Region'})
    CREATE (:Office {type: 'Regional Offices'})-[:INCLUDES]->(:Region {type: 'WHO European Region'})
    CREATE (:Office {type: 'Regional Offices'})-[:INCLUDES]->(:Region {type: 'WHO Region of the Americas'})
    CREATE (:Office {type: 'Regional Offices'})-[:INCLUDES]->(:Region {type: 'WHO South-East Asia Region'})
    CREATE (:Office {type: 'Regional Offices'})-[:INCLUDES]->(:Region {type: 'WHO Western Pacific Region'})
    CREATE (:Office {type: 'World Health Organization Regional Office For Africa'})-[:HAS]->(:Region {type: 'African Region'})
    CREATE (:Office {type: 'World Health Organization Regional Office For The Americas'})-[:HAS]->(:Region {type: 'Region Of The Americas'})
    CREATE (:OneHealth {type: 'One Health'})-[:RELATED_TO]->(:FoodSafety {type: 'Food Safety'})
    CREATE (:OpioidAnalgesics)-[:TREATS]->(:CancerPain)
    CREATE (:OralBacteria {type: 'Oral Bacteria'})-[:PRODUCES]->(:AcidProduction {type: 'Acid Production'})
    CREATE (:Organization {type: 'CodexAlimentariusCommission'})-[:DEVELOPS]->(:Concept {type: 'InternationalFoodStandards'})
    CREATE (:Organization {type: 'FAO'})-[:IS_PART_OF]->(:Organization {type: 'UN'})
    CREATE (:Organization {type: 'Food Manufacturers'})-[:SHOULD_REDUCE_IN_THEIR_PRODUCTS]->(:Nutrient {type: 'Sodium Content'})
    CREATE (:Organization {type: 'Global Anaemia Alliance'})-[:BRINGS_TOGETHER]->(:Organization {type: 'Multisectoral Partners'})
    CREATE (:Organization {type: 'Global Anaemia Alliance'})-[:CO_ESTABLISHED_WITH]->(:Organization {type: 'United Nations Childrens Fund'})
    CREATE (:Organization {type: 'Global Anaemia Alliance'})-[:ESTABLISHED_BY]->(:Organization {type: 'World Health Organization'})
    CREATE (:Organization {type: 'Global Health Organization'})-[:CONCERNED_WITH]->(:Concept {type: 'Nutrition Security'})
    CREATE (:Organization {type: 'Global Health Organization'})-[:DIVIDED_INTO]->(:GeographicArea {type: 'Geographic Regions'})
    CREATE (:Organization {type: 'Global Health Organization'})-[:GUIDED_BY]->(:Policy {type: 'Organizational Policies'})
    CREATE (:Organization {type: 'Global Health Organization'})-[:PROVIDES]->(:Information {type: 'Public Contact Information'})
    CREATE (:Organization {type: 'Government'})-[:PROMOTES]->(:Policy {type: 'Nutrition Policy'})
    CREATE (:Organization {type: 'Institute for Health Metrics and Evaluation (IHME)'})-[:ESTIMATES]->(:Exposure {type: 'Lead Exposure'})
    CREATE (:Organization {type: 'United States Renal Data System'})-[:AFFILIATED_WITH]->(:Organization {type: 'National Institutes of Health'})
    CREATE (:Organization {type: 'WHO Regional Offices'})-[:BELONGS_TO]->(:Organization {type: 'World Health Organization'})
    CREATE (:Organization {type: 'WHO'})-[:CONCERNED_WITH]->(:Field {type: 'Global Health'})
    CREATE (:Organization {type: 'WHO'})-[:DEVELOPS_PLAN_FOR]->(:HealthProgram {type: 'Maternal, Infant, and Young Child Nutrition'})
    CREATE (:Organization {type: 'WHO'})-[:DIVIDED_INTO]->(:GeographicRegion {type: 'Geographic Regions'})
    CREATE (:Organization {type: 'WHO'})-[:HAS]->(:Office {type: 'Regional Offices'})
    CREATE (:Organization {type: 'WHO'})-[:IS]->(:Concept {type: 'Global Health'})
    CREATE (:Organization {type: 'WHO'})-[:MAINTAINS]->(:Database {type: 'Global Health Observatory'})
    CREATE (:Organization {type: 'WHO'})-[:PROVIDES_GUIDELINES_FOR]->(:MedicalMeasurement {type: 'Hemoglobin Concentrations'})
    CREATE (:Organization {type: 'WHO'})-[:RESEARCHES]->(:MedicalCondition {type: 'Iron Deficiency Anemia'})
    CREATE (:Organization {type: 'World Bank'})-[:PUBLISHED]->(:Framework {type: 'Nutrition Investment Framework'})
    CREATE (:Organization {type: 'World Health Organization (WHO)'})-[:IDENTIFIES_AS_MAJOR_PUBLIC_HEALTH_CONCERN]->(:Substance {type: 'Lead'})
    CREATE (:Organization {type: 'World Health Organization (WHO)'})-[:IS]->(:GlobalHealthAuthority {type: 'Global Health Authority'})
    CREATE (:Organization {type: 'World Health Organization'})-[:ADDRESSES]->(:MedicalSpecialty {type: 'Pediatric Oncology'})
    CREATE (:Organization {type: 'World Health Organization'})-[:ADDRESSES_THE_GLOBAL_BURDEN_OF]->(:Disease {type: 'Colorectal Carcinoma'})
    CREATE (:Organization {type: 'World Health Organization'})-[:COLLABORATES_WITH]->(:Entity {type: 'National Governments'})
    CREATE (:Organization {type: 'World Health Organization'})-[:COLLABORATES_WITH]->(:Government {type: 'National Governments'})
    CREATE (:Organization {type: 'World Health Organization'})-[:COLLABORATES_WITH]->(:Organization {type: 'St Jude Childrens Research Hospital'})
    CREATE (:Organization {type: 'World Health Organization'})-[:COLLABORATES_WITH]->(:Partner {type: 'Global Partners'})
    CREATE (:Organization {type: 'World Health Organization'})-[:COLLABORATES_WITH]->(:Partnership {type: 'Global Health Partnerships'})
    CREATE (:Organization {type: 'World Health Organization'})-[:COLLECTS]->(:Data {type: 'Global Health Data'})
    CREATE (:Organization {type: 'World Health Organization'})-[:COLLECTS]->(:Data {type: 'Health Data'})
    CREATE (:Organization {type: 'World Health Organization'})-[:COMMITTED_TO_REDUCE]->(:Disease {type: 'Iron Deficiency Anaemia'})
    CREATE (:Organization {type: 'World Health Organization'})-[:CONCERNED_WITH]->(:Concept {type: 'Food Safety'})
    CREATE (:Organization {type: 'World Health Organization'})-[:CONDUCTS]->(:Research {type: 'Health Research'})
    CREATE (:Organization {type: 'World Health Organization'})-[:DEVELOPED]->(:ActionPackage {type: 'REPLACEAction Package'})
    CREATE (:Organization {type: 'World Health Organization'})-[:DEVELOPED]->(:Plan {type: 'Noncommunicable Disease Prevention Plan'})
    CREATE (:Organization {type: 'World Health Organization'})-[:DEVELOPED]->(:Plan {type: 'Trans Fat Elimination Plan'})
    CREATE (:Organization {type: 'World Health Organization'})-[:DEVELOPED]->(:Strategy {type: 'Global Nutrition Strategy'})
    CREATE (:Organization {type: 'World Health Organization'})-[:DEVELOPED]->(:Tool {type: 'Nutrient Profiling'})
    CREATE (:Organization {type: 'World Health Organization'})-[:DEVELOPED]->(:TrackingTool {type: 'Country Score Card'})
    CREATE (:Organization {type: 'World Health Organization'})-[:DEVELOPS]->(:Plan {type: 'Global Action Plan'})
    CREATE (:Organization {type: 'World Health Organization'})-[:DEVELOPS]->(:Policy {type: 'Global Health Policy'})
    CREATE (:Organization {type: 'World Health Organization'})-[:DIVIDED_INTO]->(:Region {type: 'Geographic Regions'})
    CREATE (:Organization {type: 'World Health Organization'})-[:DIVIDED_INTO]->(:Region {type: 'WHO Regions'})
    CREATE (:Organization {type: 'World Health Organization'})-[:ENDORSED]->(:Event {type: 'World Health Assembly'})
    CREATE (:Organization {type: 'World Health Organization'})-[:ENFORCES]->(:Regulation {type: 'Global Health Regulations'})
    CREATE (:Organization {type: 'World Health Organization'})-[:ENSURES]->(:Accountability {type: 'Global Health Accountability'})
    CREATE (:Organization {type: 'World Health Organization'})-[:ESTABLISHED]->(:Commission {type: 'Childhood Obesity Commission'})
    CREATE (:Organization {type: 'World Health Organization'})-[:FOCUSES_ON]->(:Field {type: 'Global Health'})
    CREATE (:Organization {type: 'World Health Organization'})-[:FOCUSES_ON]->(:Field {type: 'Global Nutrition'})
    CREATE (:Organization {type: 'World Health Organization'})-[:FOCUSES_ON]->(:Field {type: 'Nutrition'})
    CREATE (:Organization {type: 'World Health Organization'})-[:FOSTERS]->(:Partnerships {type: 'Multisectoral Partnerships'})
    CREATE (:Organization {type: 'World Health Organization'})-[:GOVERNED_BY]->(:Policy {type: 'Organizational Policies'})
    CREATE (:Organization {type: 'World Health Organization'})-[:HAS]->(:Department {type: 'Media Centre'})
    CREATE (:Organization {type: 'World Health Organization'})-[:HAS]->(:Document {type: 'Privacy policy'})
    CREATE (:Organization {type: 'World Health Organization'})-[:HAS]->(:Document {type: 'Terms of use'})
    CREATE (:Organization {type: 'World Health Organization'})-[:HAS]->(:Policy {type: 'Organizational Policies'})
    CREATE (:Organization {type: 'World Health Organization'})-[:HAS]->(:Website {type: 'Website'})
    CREATE (:Organization {type: 'World Health Organization'})-[:IMPLEMENTS]->(:Plan {type: 'Global ActionPlan For Physical Activity'})
    CREATE (:Organization {type: 'World Health Organization'})-[:INITIATED]->(:Initiative {type: 'Global Diabetes Compact'})
    CREATE (:Organization {type: 'World Health Organization'})-[:IS]->(:Concept {type: 'Global Health'})
    CREATE (:Organization {type: 'World Health Organization'})-[:IS]->(:Organization {type: 'Global Health Organization'})
    CREATE (:Organization {type: 'World Health Organization'})-[:IS_GOVERNED_BY]->(:Policy {type: 'Organizational Policies'})
    CREATE (:Organization {type: 'World Health Organization'})-[:IS_ON]->(:Platform {type: 'Ephemeral messaging platform'})
    CREATE (:Organization {type: 'World Health Organization'})-[:IS_ON]->(:Platform {type: 'Microblogging platform'})
    CREATE (:Organization {type: 'World Health Organization'})-[:IS_ON]->(:Platform {type: 'Photo sharing platform'})
    CREATE (:Organization {type: 'World Health Organization'})-[:IS_ON]->(:Platform {type: 'Professional networking platform'})
    CREATE (:Organization {type: 'World Health Organization'})-[:IS_ON]->(:Platform {type: 'Short-form video sharing platform'})
    CREATE (:Organization {type: 'World Health Organization'})-[:IS_ON]->(:Platform {type: 'Social networking platform'})
    CREATE (:Organization {type: 'World Health Organization'})-[:IS_ON]->(:Platform {type: 'Video sharing platform'})
    CREATE (:Organization {type: 'World Health Organization'})-[:IS_PRESENT_ON]->(:Platform {type: 'Digital Media Platforms'})
    CREATE (:Organization {type: 'World Health Organization'})-[:MAINTAINS]->(:Library {type: 'WHO Library'})
    CREATE (:Organization {type: 'World Health Organization'})-[:MAINTAINS]->(:Progress {type: 'Global Trans Fat Elimination Progress Monitoring'})
    CREATE (:Organization {type: 'World Health Organization'})-[:OPERATES_IN]->(:Location {type: 'Geographic Regions'})
    CREATE (:Organization {type: 'World Health Organization'})-[:OPERATES_IN]->(:Region {type: 'Geographic Regions'})
    CREATE (:Organization {type: 'World Health Organization'})-[:OPERATES_UNDER]->(:Governance {type: 'Organizational Governance'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PRESENT_ON]->(:Platform {type: 'Digital Presence'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PRODUCES]->(:Publication {type: 'Scientific Publications'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PRODUCES]->(:Publication {type: 'WHO Publications'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PROMOTES]->(:Field {type: 'Nutrition'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PROMOTES]->(:Initiative {type: 'Dietary Trans Fat Elimination'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PROMOTES]->(:Strategy {type: 'Sodium Reduction Strategies'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PROVIDES]->(:Funding {type: 'Global Health Funding'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PROVIDES]->(:Guideline {type: 'Dietary Guidelines'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PROVIDES]->(:Guideline {type: 'Nutrition Guidelines'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PROVIDES]->(:Programs {type: 'Capacity Building Programs'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PROVIDES]->(:Resource {type: 'Global Health Guidance'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PROVIDES_GUIDANCE_ON]->(:Disease {type: 'Breast Neoplasms'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PROVIDES_GUIDANCE_ON]->(:MedicalSpecialty {type: 'Radiation Oncology'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PUBLISHES]->(:Report {type: 'Global Health Reports'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PUBLISHES]->(:Report {type: 'Health Reports'})
    CREATE (:Organization {type: 'World Health Organization'})-[:REQUIRES]->(:Resource {type: 'Financial Resources'})
    CREATE (:Organization {type: 'World Health Organization'})-[:RESPONDS_TO]->(:PublicHealthEmergency {type: 'Public Health Emergencies'})
    CREATE (:Organization {type: 'World Health Organization'})-[:STRENGTHENS]->(:Surveillance {type: 'Foodborne Disease Surveillance'})
    CREATE (:Organization {type: 'World Health Organization'})-[:STRENGTHENS]->(:System {type: 'Food Safety Systems'})
    CREATE (:Organization {type: 'World Health Organization'})-[:SUPPORTS]->(:Initiative {type: 'Trans Fat Elimination Initiative'})
    CREATE (:Organization {type: 'World Health Organization'})-[:SUPPORTS]->(:PreventionStrategy {type: 'Anaemia Prevention'})
    CREATE (:Organization {type: 'World Health Organization'})-[:SUPPORTS_AND_PROMOTES]->(:Prevention {type: 'Diabetes Prevention and Control'})
    CREATE (:Organization {type: 'World Health Organization'})-[:WORKS_TO_ELIMINATE]->(:Disease {type: 'Cervical Neoplasms'})
    CREATE (:Organization {type: 'World Health Organization'})-[:WORKS_WITH]->(:Organization {type: 'Global Health Partners'})
    CREATE (:Organization {type: 'World Health Organization'})-[:COLLABORATES_WITH]->(:Organization {type: 'Codex Alimentarius Commission'})
    CREATE (:Organization {type: 'World Health Organization'})-[:COLLABORATES_WITH]->(:Partner {type: 'Collaborative Partners'})
    CREATE (:Organization {type: 'World Health Organization'})-[:COLLABORATES_WITH]->(:Partnership {type: 'Global Partnerships'})
    CREATE (:Organization {type: 'World Health Organization'})-[:CONDUCTS]->(:Research {type: 'Research And Development'})
    CREATE (:Organization {type: 'World Health Organization'})-[:FOCUSES_ON]->(:Concept {type: 'Food Safety'})
    CREATE (:Organization {type: 'World Health Organization'})-[:FOCUSES_ON]->(:Field {type: 'Nutrition'})
    CREATE (:Organization {type: 'World Health Organization'})-[:GUIDED_BY]->(:Framework {type: 'Governance Framework'})
    CREATE (:Organization {type: 'World Health Organization'})-[:ISSUES]->(:Appeal {type: 'Emergency Appeal'})
    CREATE (:Organization {type: 'World Health Organization'})-[:ISSUES]->(:Appeal {type: 'Emergency Response Appeals'})
    CREATE (:Organization {type: 'World Health Organization'})-[:OPERATES_IN]->(:Concept {type: 'Geographic Regions'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PRIORITIZES]->(:Mechanism {type: 'Accountability Mechanisms'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PROVIDES]->(:FinancialSupport {type: 'Financial Support'})
    CREATE (:Organization {type: 'World Health Organization'})-[:PROVIDES]->(:Support {type: 'Financial Support'})
    CREATE (:Organization {type: 'World  Health Organization'})-[:PUBLISHES]->(:Report {type: 'Technical Reports'})
    CREATE (:Organization {type: 'WorldH  ealth Organization'})-[:WORKS_TOWARDS]->(:Field {type: 'Global Health'})
    CREATE (:Orthotics {type: 'Orthotics'})-[:IS]->(:AssistiveDevices {type: 'Assistive Devices'})
    CREATE (:Osteoarthritis {type: 'Osteoarthritis'})-[:CAUSES]->(:JointStiffness {type: 'Joint Stiffness'})
    CREATE (:Osteoarthritis {type: 'Osteoarthritis'})-[:CAUSES]->(:JointSwelling {type: 'Joint Swelling'})
    CREATE (:Osteoarthritis {type: 'Osteoarthritis'})-[:CAUSES]->(:MusculoskeletalPain {type: 'Musculoskeletal Pain'})
    CREATE (:Osteoarthritis {type: 'Osteoarthritis'})-[:IS]->(:MusculoskeletalDisorder {type: 'Musculoskeletal Disorder'})
    CREATE (:Osteoarthritis {type: 'Osteoarthritis'})-[:MAY_BE_CAUSED_BY]->(:Aging {type: 'Aging'})
    CREATE (:Osteoarthritis {type: 'Osteoarthritis'})-[:MAY_BE_CAUSED_BY]->(:Obesity {type: 'Obesity'})
    CREATE (:Osteoarthritis {type: 'Osteoarthritis'})-[:MAY_BE_CAUSED_BY]->(:RepetitiveJointOveruse {type: 'Repetitive Joint Overuse'})
    CREATE (:Osteoarthritis {type: 'Osteoarthritis'})-[:MAY_BE_CAUSED_BY]->(:TraumaticJointInjury {type: 'Traumatic Joint Injury'})
    CREATE (:Osteoarthritis {type: 'Osteoarthritis'})-[:MAY_BE_MANAGED_WITH]->(:MultimodalRehabilitation {type: 'Multimodal Rehabilitation'})
    CREATE (:Osteoarthritis {type: 'Osteoarthritis'})-[:MAY_BE_REDUCED_BY]->(:BalancedDiet {type: 'Balanced Diet'})
    CREATE (:Osteoarthritis {type: 'Osteoarthritis'})-[:MAY_BE_REDUCED_BY]->(:RegularPhysicalActivity {type: 'Regular Physical Activity'})
    CREATE (:Osteoarthritis {type: 'Osteoarthritis'})-[:MAY_BE_TREATED_WITH]->(:JointReplacementSurgery {type: 'Joint Replacement Surgery'})
    CREATE (:Osteoarthritis {type: 'Osteoarthritis'})-[:OFTEN_AFFECTS]->(:HandJoint {type: 'Hand Joint'})
    CREATE (:Osteoarthritis {type: 'Osteoarthritis'})-[:OFTEN_AFFECTS]->(:HipJoint {type: 'Hip Joint'})
    CREATE (:Osteoarthritis {type: 'Osteoarthritis'})-[:OFTEN_AFFECTS]->(:KneeJoint {type: 'Knee Joint'})
    CREATE (:OsteoarthritisManagement {type: 'Osteoarthritis Management'})-[:REQUIRES]->(:PersonalizedCare {type: 'Personalized Care'})
    CREATE (:Overweight {type: 'Overweight'})-[:RELATED_TO]->(:Obesity {type: 'Obesity'})
    CREATE (:OverweightAndObesity {type: 'Overweight and Obesity'})-[:RESULTS_IN]->(:NonCommunicableDiseases {type: 'Non-Communicable Diseases'})
    CREATE (:Parasite {type: 'Foodborne Parasites'})-[:TRANSMITTED_THROUGH]->(:Food {type: 'Food'})
    CREATE (:PartiallyHydrogenatedOils {type: 'Partially Hydrogenated Oils (PHOs)'})-[:CAN_BE_FOUND_IN]->(:FriedFoods {type: 'Fried Foods'})
    CREATE (:PartiallyHydrogenatedOils {type: 'Partially Hydrogenated Oils (PHOs)'})-[:CAN_BE_FOUND_IN]->(:Margarine {type: 'Margarine'})
    CREATE (:PartiallyHydrogenatedOils {type: 'Partially Hydrogenated Oils (PHOs)'})-[:CAN_BE_FOUND_IN]->(:VegetableShortening {type: 'Vegetable Shortening'})
    CREATE (:Partnership {type: 'Anaemia Action Alliance'})-[:BRINGS_TOGETHER]->(:Stakeholder {type: 'Multisectoral Partners'})
    CREATE (:Partnership {type: 'Anaemia Action Alliance'})-[:ESTABLISHED_BY]->(:Organization {type: 'World Health Organization And UNICEF'})
    CREATE (:Partnerships {type: 'Multisectoral Partnerships'})-[:FACILITATES]->(:Engagement {type: 'Stakeholder Engagement'})
    CREATE (:PatientEducation {type: 'Patient Education'})-[:COMPLEMENTS]->(:Counselling {type: 'Counselling'})
$$) AS (a agtype);
